version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/agents"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/base-shell"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/chat"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/dynamic-views"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/storage"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/skills"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/settings"
    schedule:
      interval: "weekly"
