"""Agent-facing Calendar operation and reference manifests."""

from __future__ import annotations

from typing import Any


def operations_manifest(app_id: str = "calendar") -> dict[str, Any]:
    """Return a compact operation manifest for CLI and MCP users."""
    return {
        "action": "operations.manifest",
        "app_id": app_id,
        "schema_version": "1",
        "default_action": "operations.manifest",
        "commands": [
            {
                "surface": "cli",
                "name": "calendar",
                "description": "Manage workspace calendar events and availability. Calling without arguments returns this manifest.",
            },
            {
                "surface": "cli",
                "name": "calendar-reference",
                "description": "Search, resolve, and summarize calendar event references.",
            },
        ],
        "tools": [
            {"surface": "mcp", "name": "calendar_operations_manifest", "operation": "operations.manifest"},
            {"surface": "mcp", "name": "calendar_connections.list", "operation": "calendar_connections.list"},
            {"surface": "mcp", "name": "calendar_calendars.list", "operation": "calendar_calendars.list"},
            {"surface": "mcp", "name": "calendar_calendars.select", "operation": "calendar_calendars.select"},
            {"surface": "mcp", "name": "calendar_connections.start_oauth", "operation": "calendar_connections.start_oauth"},
            {"surface": "mcp", "name": "calendar_connections.disconnect", "operation": "calendar_connections.disconnect"},
            {"surface": "mcp", "name": "calendar_sync", "operation": "calendar_sync"},
            {"surface": "mcp", "name": "calendar_list_events", "operation": "list"},
            {"surface": "mcp", "name": "calendar_create_event", "operation": "create"},
            {"surface": "mcp", "name": "calendar_update_event", "operation": "update"},
            {"surface": "mcp", "name": "calendar_delete_event", "operation": "delete"},
            {"surface": "mcp", "name": "calendar_move_event", "operation": "move"},
            {"surface": "mcp", "name": "calendar_check_availability", "operation": "check_availability"},
            {"surface": "mcp", "name": "calendar_find_free_time", "operation": "find_free_time"},
            {"surface": "mcp", "name": "calendar_view_filter", "operation": "view_filter"},
            {"surface": "mcp", "name": "calendar_set_view_filter", "operation": "set_view_filter"},
            {"surface": "mcp", "name": "calendar_set_custom_view", "operation": "set_custom_view"},
            {"surface": "mcp", "name": "calendar_clear_custom_view", "operation": "clear_custom_view"},
            {"surface": "mcp", "name": "calendar_reference_manifest", "operation": "references.manifest"},
            {"surface": "mcp", "name": "calendar_reference_search", "operation": "references.search"},
            {"surface": "mcp", "name": "calendar_reference_resolve", "operation": "references.resolve"},
            {"surface": "mcp", "name": "calendar_reference_summarize", "operation": "references.summarize"},
        ],
        "operations": [
            {
                "action": "calendar_connections.list",
                "description": "List Google Calendar connection records known to Calendar.",
                "payload_profile": "connection_list",
            },
            {
                "action": "calendar_calendars.list",
                "description": "List known Google calendars and local sync selection for each connection.",
                "optional": ["connection_id"],
                "payload_profile": "calendar_source_list",
                "provider": "google_calendar",
            },
            {
                "action": "calendar_calendars.select",
                "description": "Enable or disable local sync selection for one known Google calendar.",
                "required": ["connection_id", "calendar_id"],
                "optional": ["selected", "sync_enabled"],
                "payload_profile": "calendar_source_selection",
                "provider": "google_calendar",
            },
            {
                "action": "calendar_connections.start_oauth",
                "description": "Start Google Calendar OAuth and return an authorization URL. OAuth completion is backend-only.",
                "optional": ["redirect_uri", "scope"],
                "payload_profile": "oauth_authorization",
                "provider": "google_calendar",
            },
            {
                "action": "calendar_connections.disconnect",
                "description": "Disconnect one Google Calendar connection and retire its resource-scoped refresh token.",
                "required": ["connection_id"],
                "payload_profile": "connection_disconnect_result",
                "provider": "google_calendar",
            },
            {
                "action": "calendar_sync",
                "description": "Synchronize Google Calendar calendars and events into local Calendar state.",
                "required": ["connection_id"],
                "optional": ["calendar_id", "sync_token", "full_sync"],
                "payload_profile": "google_sync_result",
                "provider": "google_calendar",
            },
            {
                "action": "list",
                "description": "List calendar events, compact by default for agent surfaces.",
                "optional": [
                    "start_after",
                    "end_before",
                    "query",
                    "tags",
                    "category",
                    "attendee",
                    "offset",
                    "limit",
                    "profile",
                    "include_description",
                ],
                "payload_profile": "compact_by_default",
            },
            {
                "action": "create",
                "description": "Create one event. Event ids are generated by Calendar.",
                "required": ["title", "startTime", "endTime"],
                "optional": [
                    "description",
                    "color",
                    "category",
                    "attendees",
                    "tags",
                    "status",
                    "timezone",
                    "location",
                    "organizer",
                    "all_day",
                    "source",
                    "external_refs",
                    "recurrence",
                    "reminders",
                    "idempotency_key",
                    "conflict_policy",
                ],
                "payload_profile": "single_event_full",
            },
            {
                "action": "update",
                "description": "Update one event by id.",
                "required": ["id", "expected_revision"],
                "optional": [
                    "title",
                    "description",
                    "startTime",
                    "endTime",
                    "status",
                    "timezone",
                    "location",
                    "organizer",
                    "all_day",
                    "source",
                    "external_refs",
                    "recurrence",
                    "reminders",
                    "conflict_policy",
                ],
                "payload_profile": "single_event_full",
            },
            {
                "action": "delete",
                "description": "Delete one event by id.",
                "required": ["id", "expected_revision"],
                "payload_profile": "single_delete_result",
            },
            {
                "action": "move",
                "description": "Move one event to a new start time or to the first free slot in a bounded window.",
                "required": ["id", "expected_revision"],
                "optional": [
                    "startTime",
                    "endTime",
                    "move_strategy",
                    "first_free",
                    "start_after",
                    "end_before",
                    "attendees",
                    "attendee",
                    "conflict_policy",
                ],
                "payload_profile": "single_event_full",
            },
            {
                "action": "check_availability",
                "description": "Check whether a specific time window is free and return compact conflicting events.",
                "required": ["startTime", "endTime"],
                "optional": ["attendees", "attendee", "ignore_event_id"],
                "payload_profile": "availability_result",
            },
            {
                "action": "find_free_time",
                "description": "Find open slots in a time window using current events as busy intervals.",
                "required": ["start_after", "end_before"],
                "optional": ["duration_minutes", "attendees", "attendee", "limit", "ignore_event_id"],
                "payload_profile": "compact_slots",
            },
            {
                "action": "view_filter",
                "description": "Read the current Calendar view state used for reference-aware navigation.",
                "payload_profile": "single_view_state",
            },
            {
                "action": "set_view_filter",
                "description": "Set Calendar's query and time-window filter for a standard view surface.",
                "optional": [
                    "query",
                    "start_after",
                    "end_before",
                    "category",
                    "attendee",
                    "tags",
                    "conflicts_only",
                    "preserve_custom",
                ],
                "payload_profile": "single_view_state",
            },
            {
                "action": "set_custom_view",
                "description": "Curate Calendar to a supplied list of event references.",
                "required": ["entity_ids"],
                "optional": ["title", "query"],
                "payload_profile": "single_view_state",
            },
            {
                "action": "clear_custom_view",
                "description": "Return Calendar to the default view state.",
                "payload_profile": "single_view_state",
            },
            {
                "action": "references.search",
                "description": "Search event references for mention pickers and compact agent context.",
                "optional": ["query", "limit"],
                "payload_profile": "compact_references",
            },
            {
                "action": "references.resolve",
                "description": "Resolve one calendar event reference by entity id.",
                "required": ["entity_id"],
                "payload_profile": "single_reference",
            },
            {
                "action": "references.summarize",
                "description": "Return a token-efficient summary for one event reference.",
                "required": ["entity_id"],
                "payload_profile": "single_reference_summary",
            },
        ],
        "payload_profiles": {
            "calendar_connections.list": "connection_list",
            "calendar_calendars.list": "calendar_source_list",
            "calendar_calendars.select": "calendar_source_selection",
            "calendar_connections.start_oauth": "oauth_authorization",
            "calendar_connections.disconnect": "connection_disconnect_result",
            "calendar_sync": "google_sync_result",
            "list": "compact_by_default",
            "list.full": "explicit_full_list",
            "create": "single_event_full",
            "update": "single_event_full",
            "delete": "single_delete_result",
            "move": "single_event_full",
            "check_availability": "availability_result",
            "find_free_time": "compact_slots",
            "view_filter": "single_view_state",
            "set_view_filter": "single_view_state",
            "set_custom_view": "single_view_state",
            "clear_custom_view": "single_view_state",
            "references.search": "compact_results",
            "references.resolve": "single_reference",
            "references.summarize": "single_reference_summary",
        },
        "id_patterns": {"event_id": "evt_<hex>"},
        "allowed_values": {
            "color": ["blue", "green", "orange", "pink", "purple", "red"],
            "profile": ["compact", "full"],
            "event_status": ["cancelled", "confirmed", "tentative"],
            "conflict_policy": ["allow", "reject", "warn"],
            "move_strategy": ["fixed_time", "first_free"],
        },
        "event_model": {
            "required": ["id", "title", "startTime", "endTime", "status", "timezone", "all_day", "created_at", "updated_at", "revision"],
            "metadata": [
                "location",
                "organizer",
                "source",
                "external_refs",
                "recurrence",
                "reminders",
                "idempotency_key",
            ],
            "generated_on_create": ["id", "created_at", "updated_at", "revision"],
            "updated_on_mutation": ["updated_at", "revision"],
            "optimistic_concurrency": {
                "field": "expected_revision",
                "applies_to": ["update", "delete", "move"],
                "conflict_status_code": 409,
            },
            "idempotency": {
                "field": "idempotency_key",
                "applies_to": ["create"],
                "replay_status_code": 200,
                "immutable_after_create": True,
            },
        },
        "policy": {
            "sandbox_agent_allowed": True,
            "requires_workspace_context": True,
            "requires_full_access": False,
        },
    }


def reference_manifest(app_id: str = "calendar") -> dict[str, Any]:
    """Return common reference metadata for event references."""
    return {
        "action": "references.manifest",
        "app_id": app_id,
        "entity_types": [
            {
                "entity_type": "event",
                "display_name": "Calendar Event",
                "searchable": True,
                "resolvable": True,
                "summarizable": True,
                "deep_link_supported": True,
            }
        ],
    }
