"""Vocabulary used by deterministic runtime thread title generation."""

from __future__ import annotations


STOPWORDS = {
    "a",
    "ad",
    "agli",
    "ai",
    "al",
    "alla",
    "alle",
    "allo",
    "an",
    "and",
    "anche",
    "are",
    "can",
    "che",
    "ciao",
    "come",
    "con",
    "cosa",
    "could",
    "da",
    "dal",
    "de",
    "dei",
    "del",
    "della",
    "delle",
    "di",
    "do",
    "e",
    "ed",
    "for",
    "from",
    "gli",
    "ho",
    "i",
    "il",
    "in",
    "is",
    "la",
    "le",
    "lo",
    "me",
    "mi",
    "mio",
    "mia",
    "my",
    "nel",
    "nella",
    "nello",
    "non",
    "of",
    "ok",
    "on",
    "o",
    "or",
    "per",
    "please",
    "quella",
    "quelle",
    "quelli",
    "quello",
    "questa",
    "queste",
    "questi",
    "questo",
    "should",
    "su",
    "sul",
    "sulla",
    "the",
    "this",
    "to",
    "un",
    "una",
    "uno",
    "us",
    "use",
    "using",
    "would",
    "you",
}

LOW_SIGNAL_KEYS = {
    "allora",
    "attenta",
    "basata",
    "basate",
    "basato",
    "baste",
    "bene",
    "capire",
    "ci",
    "coerente",
    "deve",
    "devono",
    "devo",
    "dici",
    "dirmi",
    "dovrebbe",
    "dovrebbero",
    "dentro",
    "era",
    "erano",
    "essere",
    "entro",
    "faccio",
    "faccia",
    "facciamo",
    "facciano",
    "fai",
    "fammi",
    "fare",
    "farli",
    "fatte",
    "fatto",
    "files",
    "find",
    "folders",
    "frase",
    "funziona",
    "giusti",
    "help",
    "here",
    "implementato",
    "invece",
    "lavorando",
    "lavorare",
    "lavoriamo",
    "ma",
    "massimo",
    "messaggio",
    "mette",
    "mettere",
    "mettendo",
    "miglior",
    "molto",
    "no",
    "obiettivo",
    "parla",
    "parole",
    "parta",
    "perche",
    "pero",
    "poter",
    "potresti",
    "praticamente",
    "prime",
    "primo",
    "puoi",
    "punteggiatura",
    "punti",
    "quando",
    "scrivere",
    "scrivi",
    "serve",
    "show",
    "si",
    "sistema",
    "sono",
    "stata",
    "state",
    "stati",
    "stato",
    "stiamo",
    "that",
    "togliendo",
    "tutte",
    "utilizzare",
    "vediamo",
    "voglio",
    "vorrei",
    "write",
    "yet",
}

ACTION_REPLACEMENTS = {
    "analisi": "Analisi",
    "analizza": "Analisi",
    "analizzare": "Analisi",
    "analyze": "Analysis",
    "controlla": "Verifica",
    "controllare": "Verifica",
    "conversione": "Conversione",
    "convert": "Conversione",
    "converti": "Conversione",
    "convertire": "Conversione",
    "correggere": "Fix",
    "correggi": "Fix",
    "debug": "Debug",
    "debugga": "Debug",
    "debuggare": "Debug",
    "esamina": "Analisi",
    "esaminare": "Analisi",
    "fix": "Fix",
    "fixa": "Fix",
    "fixare": "Fix",
    "migliora": "Migliorare",
    "migliorare": "Migliorare",
    "miglioramento": "Migliorare",
    "migliorie": "Migliorare",
    "problema": "Problema",
    "ricerca": "Ricerca",
    "risolvere": "Fix",
    "risolvi": "Fix",
    "review": "Review",
    "trova": "Ricerca",
    "trovare": "Ricerca",
    "verifica": "Verifica",
    "verificare": "Verifica",
}

IMPLEMENTATION_ACTIONS = {
    "build": "Build",
    "crea": "Creazione",
    "creare": "Creazione",
    "create": "Creation",
    "genera": "Generazione",
    "generare": "Generazione",
    "generate": "Generation",
    "implementa": "Implementazione",
    "implementare": "Implementazione",
    "implementi": "Implementazione",
}

FORMAT_KEYS = {"doc", "docx", "md", "markdown", "pdf", "ppt", "pptx", "xlsx"}
CONVERSION_KEYS = {"conversione", "convert", "converti", "convertire", "trasforma", "trasformare"}
IMPROVEMENT_KEYS = {"migliora", "migliorare", "miglioramento", "migliorie"}
FIX_KEYS = {"correggere", "correggi", "fix", "fixa", "fixare", "risolvere", "risolvi"}
INTENT_KEYS = CONVERSION_KEYS | IMPROVEMENT_KEYS | FIX_KEYS | {
    "analisi",
    "analizza",
    "controlla",
    "dovrebbe",
    "implementa",
    "problema",
    "ricerca",
    "trova",
    "verifica",
    "voglio",
    "vorrei",
}

PRODUCT_KEYS = {
    "agents",
    "agenti",
    "app",
    "backend",
    "chat",
    "frontend",
    "memory",
    "storage",
    "store",
}

STRONG_TOPIC_KEYS = {
    "anomalie",
    "budget",
    "caricamento",
    "cartella",
    "cartelle",
    "cliente",
    "drop",
    "drag",
    "fallback",
    "file",
    "folder",
    "follow",
    "loading",
    "mail",
    "markdown",
    "naming",
    "nomenclatura",
    "pdf",
    "reorder",
    "sidebar",
    "skeleton",
    "test",
    "title",
    "titoli",
}

DISPLAY_REPLACEMENTS = {
    "agenti": "Agenti",
    "agents": "Agenti",
    "app": "App",
    "backend": "Backend",
    "chat": "Chat",
    "doc": "DOC",
    "docx": "DOCX",
    "frontend": "Frontend",
    "md": "Markdown",
    "memory": "Memory",
    "pdf": "PDF",
    "ppt": "PPT",
    "pptx": "PPTX",
    "storage": "Storage",
    "store": "Store",
    "xlsx": "XLSX",
}
