"""Compact Storage CLI and MCP operations manifest."""

from __future__ import annotations

from typing import Any


STORAGE_ACTIONS = [
    "operations.manifest",
    "catalog",
    "file.catalog.list",
    "view_filter",
    "set_view_filter",
    "set_custom_view",
    "clear_custom_view",
    "file_info",
    "read_file",
    "write_file",
    "file.content.read",
    "file.content.write",
    "upload_file",
    "preview_text",
    "file.preview.text",
    "preview_table",
    "file.preview.table",
    "render_preview",
    "file.preview.render",
    "render_thumbnail",
    "update_markdown_file",
    "create_folder",
    "read_folder",
    "download_folder",
    "delete_folder",
    "move_file",
    "move_folder",
    "move_items",
    "delete_file",
    "drive_connections.list",
    "drive_connections.start_oauth",
    "drive_connections.disconnect",
    "drive_list_roots",
    "drive_list_children",
    "drive_sync",
    "drive_search",
    "drive_read",
    "drive_preview",
    "drive_export",
    "drive_index",
    "drive_mark_indexed",
    "drive_write",
    "drive_rename",
    "drive_move",
    "drive_trash",
    "references.manifest",
    "references.search",
    "references.resolve",
    "references.summarize",
    "health.check",
]

STORAGE_ACTION_ALIASES = {
    "write": "file.content.write",
    "write-file": "file.content.write",
    "write-content": "file.content.write",
    "read_file": "file.content.read",
}


def operations_manifest_payload() -> dict[str, Any]:
    """Return the compact agent-facing contract for Storage operations."""
    return {
        "app_id": "storage",
        "schema_version": "1",
        "default_action": "operations.manifest",
        "commands": [
            {
                "surface": "cli",
                "name": "storage",
                "description": "Inspect, search, preview, read, write, move, and delete workspace Storage files.",
            }
        ],
        "tools": [
            {
                "surface": "mcp",
                "name": "maverick_storage",
                "description": "Generic Storage operation runner for less common actions.",
            },
            {"surface": "mcp", "name": "storage_list_files", "operation": "catalog"},
            {"surface": "mcp", "name": "storage_file_info", "operation": "file_info"},
            {"surface": "mcp", "name": "storage_read_file", "operation": "file.content.read"},
            {"surface": "mcp", "name": "storage_preview_text", "operation": "file.preview.text"},
            {"surface": "mcp", "name": "storage_preview_table", "operation": "file.preview.table"},
            {"surface": "mcp", "name": "storage_write_file", "operation": "file.content.write"},
            {"surface": "mcp", "name": "storage_drive_list_roots", "operation": "drive_list_roots"},
            {"surface": "mcp", "name": "storage_drive_list_children", "operation": "drive_list_children"},
            {"surface": "mcp", "name": "storage_drive_search", "operation": "drive_search"},
            {"surface": "mcp", "name": "storage_drive_read", "operation": "drive_read"},
            {"surface": "mcp", "name": "storage_drive_preview", "operation": "drive_preview"},
            {"surface": "mcp", "name": "storage_drive_export", "operation": "drive_export"},
            {"surface": "mcp", "name": "storage_drive_index", "operation": "drive_index"},
            {"surface": "mcp", "name": "storage_drive_mark_indexed", "operation": "drive_mark_indexed"},
            {"surface": "mcp", "name": "storage_drive_write", "operation": "drive_write", "tool_profile": "remote_write"},
            {"surface": "mcp", "name": "storage_drive_rename", "operation": "drive_rename", "tool_profile": "remote_write"},
            {"surface": "mcp", "name": "storage_drive_move", "operation": "drive_move", "tool_profile": "remote_write"},
            {"surface": "mcp", "name": "storage_drive_trash", "operation": "drive_trash", "tool_profile": "remote_delete"},
            {"surface": "mcp", "name": "storage_reference_search", "operation": "references.search"},
            {"surface": "mcp", "name": "storage_reference_resolve", "operation": "references.resolve"},
            {"surface": "mcp", "name": "storage_reference_summarize", "operation": "references.summarize"},
        ],
        "recommended": [
            {
                "task": "list_workspace_files",
                "operation": "catalog",
                "calls_required": 1,
                "example": {"action": "catalog", "limit": 20},
            },
            {
                "task": "read_one_file",
                "operation": "file.content.read",
                "calls_required": 1,
                "example": {"action": "file.content.read", "workspace_relative_path": "storage/generated/report.md"},
            },
            {
                "task": "create_or_overwrite_generated_file",
                "operation": "file.content.write",
                "calls_required": 1,
                "example": {
                    "action": "file.content.write",
                    "workspace_relative_path": "storage/generated/report.md",
                    "mode": "overwrite",
                    "content": "# Report",
                },
            },
        ],
        "operations": [
            {
                "action": "catalog",
                "aliases": ["file.catalog.list"],
                "description": "List files and folders from the workspace Storage inventory.",
                "optional": [
                    "query",
                    "role",
                    "kind",
                    "folder_path",
                    "file_ids",
                    "workspace_relative_paths",
                    "offset",
                    "limit",
                ],
                "payload_profile": "paginated_metadata",
            },
            {
                "action": "file_info",
                "description": "Return metadata for one file by role/path or workspace_relative_path.",
                "required_any": ["workspace_relative_path", "role + relative_path"],
                "payload_profile": "single_record_metadata",
            },
            {
                "action": "file.content.read",
                "aliases": ["read_file"],
                "description": "Read one file as bounded base64 content.",
                "required_any": ["workspace_relative_path", "role + relative_path"],
                "optional": ["max_bytes"],
                "payload_profile": "explicit_content",
            },
            {
                "action": "file.content.write",
                "aliases": ["write", "write_file", "write-file", "write-content"],
                "description": "Create or overwrite one workspace Storage file.",
                "required_any": ["workspace_relative_path", "role + relative_path"],
                "required_one_of": ["content", "content_base64"],
                "optional": ["mode"],
                "payload_profile": "single_write_result",
            },
            {
                "action": "preview_text",
                "aliases": ["file.preview.text"],
                "description": "Extract a bounded text preview for supported files.",
                "required_any": ["workspace_relative_path", "role + relative_path"],
                "optional": ["max_chars"],
                "payload_profile": "bounded_preview",
            },
            {
                "action": "preview_table",
                "aliases": ["file.preview.table"],
                "description": "Extract bounded table data for CSV and spreadsheet files.",
                "required_any": ["workspace_relative_path", "role + relative_path"],
                "optional": ["max_rows", "max_columns"],
                "payload_profile": "bounded_table_preview",
            },
            {
                "action": "references.search",
                "description": "Search Storage file or folder app references.",
                "optional": ["query", "entity_type", "limit"],
                "payload_profile": "compact_references",
            },
            {
                "action": "references.resolve",
                "description": "Resolve one Storage file or folder app reference.",
                "required": ["entity_id"],
                "optional": ["entity_type"],
                "payload_profile": "single_reference",
            },
            {
                "action": "references.summarize",
                "description": "Summarize one Storage file or folder app reference.",
                "required": ["entity_id"],
                "optional": ["entity_type"],
                "payload_profile": "single_reference_summary",
            },
            {
                "action": "drive_list_roots",
                "description": "List Google Drive roots for one Storage-owned Drive connection.",
                "required": ["connection_id"],
                "optional": ["limit", "page_token"],
                "payload_profile": "remote_provider_metadata",
            },
            {
                "action": "drive_list_children",
                "description": "List children under one Drive parent id and normalize them as Storage files and folders.",
                "required": ["connection_id"],
                "required_any": ["parent_drive_file_id", "drive_file_id"],
                "optional": ["limit", "page_token"],
                "payload_profile": "remote_provider_metadata",
            },
            {
                "action": "drive_search",
                "description": "Run a bounded Google Drive search through Storage and return stable Storage file ids.",
                "required": ["connection_id"],
                "optional": ["query", "parent_drive_file_id", "limit"],
                "payload_profile": "remote_provider_metadata",
            },
            {
                "action": "drive_read",
                "description": "Read bounded bytes from one Google Drive file through Storage without exposing Google tokens.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "optional": ["max_bytes"],
                "payload_profile": "remote_bounded_content",
            },
            {
                "action": "drive_preview",
                "description": "Return a bounded Drive preview. Storage downloads binary files and centrally exports Google Docs, Sheets, and Slides to readable text.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "optional": ["max_bytes", "max_chars"],
                "payload_profile": "remote_bounded_preview",
            },
            {
                "action": "drive_export",
                "description": "Export Google Docs, Sheets, and Slides through Drive files.export with Storage-owned format selection and the Google 10 MB export limit.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "optional": ["export_mime_type", "max_bytes"],
                "payload_profile": "remote_bounded_content",
            },
            {
                "action": "drive_index",
                "description": "Prepare a bounded Memory ingestion payload for one Google Drive file using Storage preview/export and a stable Storage reference.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "optional": ["max_bytes", "max_chars <= 20000"],
                "payload_profile": "remote_memory_source",
            },
            {
                "action": "drive_mark_indexed",
                "description": "Mark one Drive Storage reference indexed after Memory ingest succeeds. This is the post-ingest acknowledgement for agent orchestration.",
                "required": ["stable_storage_file_id"],
                "optional": ["source_version", "memory_node_id", "memory_external_ref_id", "memory_source_version_id"],
                "payload_profile": "remote_index_ack",
            },
            {
                "action": "drive_write",
                "description": "Upload a new Drive file into a folder or update binary Drive file content where the Drive API allows it. Requires Drive write capabilities and emits an audit event.",
                "required_any": ["connection_id + parent_drive_file_id + file_name", "connection_id + drive_file_id", "stable_storage_file_id"],
                "required_one_of": ["content", "content_base64"],
                "optional": ["content_type"],
                "payload_profile": "remote_write_result",
            },
            {
                "action": "drive_rename",
                "description": "Rename one Google Drive file after capability checks. Emits an audit event.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "required": ["new_name"],
                "payload_profile": "remote_write_result",
            },
            {
                "action": "drive_move",
                "description": "Move one Google Drive file to a target Drive folder after source and target capability checks. Emits an audit event.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "required": ["target_parent_drive_file_id"],
                "payload_profile": "remote_write_result",
            },
            {
                "action": "drive_trash",
                "description": "Trash one Google Drive file after delete capability checks. Requires confirm=true or explicit delete_policy and emits an audit event.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "required_any_policy": ["confirm=true", "delete_policy"],
                "payload_profile": "remote_delete_result",
            },
        ],
        "payload_profiles": {
            "operations.manifest": "compact_default",
            "catalog": "explicit_action_paginated",
            "file.catalog.list": "explicit_action_paginated",
            "file_info": "metadata_only",
            "file.content.read": "explicit_file_content_only",
            "preview_text": "bounded_preview_only",
            "file.preview.text": "bounded_preview_only",
            "preview_table": "bounded_table_preview_only",
            "file.preview.table": "bounded_table_preview_only",
            "references.search": "compact_results",
            "references.resolve": "single_reference",
            "references.summarize": "single_reference_summary",
            "drive_list_roots": "remote_provider_metadata",
            "drive_list_children": "remote_provider_metadata",
            "drive_search": "remote_provider_metadata",
            "drive_read": "remote_bounded_content",
            "drive_preview": "remote_bounded_preview",
            "drive_export": "remote_bounded_content",
            "drive_index": "remote_memory_source",
            "drive_mark_indexed": "remote_index_ack",
            "drive_write": "remote_write_result",
            "drive_rename": "remote_write_result",
            "drive_move": "remote_write_result",
            "drive_trash": "remote_delete_result",
        },
        "payload_profile_details": {
            "remote_memory_source": {
                "returns": [
                    "status=ready_for_memory",
                    "source_version",
                    "preview_text <= 20000 chars",
                    "preview_truncated",
                    "Storage text extraction for supported binary Office Drive files when Drive preview has no preview_text",
                    "memory_source.source_kind=remote_storage_file",
                    "memory_source.metadata.stable_storage_file_id",
                    "does not mark indexed until drive_mark_indexed",
                ],
            },
            "remote_index_ack": {
                "returns": ["status=indexed", "stable_storage_file_id", "source_version", "memory ack ids when provided", "file.index_status=indexed"],
            },
        },
        "aliases": STORAGE_ACTION_ALIASES,
        "id_patterns": {
            "file_id": "file_<uuid>",
            "folder_id": "<role>:<percent-encoded-relative-path>/",
            "workspace_relative_path": "storage/(uploaded|generated)/<relative-path>",
            "google_drive_file": "stable_storage_file_id file_<hash> or connection_id + drive_file_id",
        },
        "policy": {
            "sandbox_agent_allowed": True,
            "requires_workspace_context": True,
            "requires_full_access": False,
            "remote_drive": {
                "read_tools": ["drive_list_roots", "drive_list_children", "drive_search", "drive_read", "drive_preview", "drive_export", "drive_index", "drive_mark_indexed"],
                "write_tools": ["drive_write", "drive_rename", "drive_move"],
                "delete_tools": ["drive_trash"],
                "delete_requires": ["confirm=true", "delete_policy"],
            },
        },
    }
