"""Compact Storage CLI and MCP operations manifest."""

from __future__ import annotations

from typing import Any


STORAGE_ACTIONS = [
    "operations.manifest",
    "catalog",
    "file.catalog.list",
    "view_filter",
    "set_view_filter",
    "set_custom_view",
    "clear_custom_view",
    "file_info",
    "read_file",
    "write_file",
    "file.content.read",
    "read_text",
    "file.text.read",
    "file.content.write",
    "image.inspect",
    "image.compose_pair",
    "image.compose_side_by_side",
    "upload_file",
    "local_upload_session.start",
    "local_upload_session.status",
    "local_upload_session.chunk",
    "local_upload_session.cancel",
    "preview_text",
    "file.preview.text",
    "preview_table",
    "file.preview.table",
    "render_preview",
    "file.preview.render",
    "render_thumbnail",
    "update_markdown_file",
    "create_folder",
    "read_folder",
    "download_folder",
    "delete_folder",
    "move_file",
    "move_folder",
    "move_items",
    "delete_file",
    "drive_connections.list",
    "drive_connections.start_oauth",
    "drive_connections.disconnect",
    "drive_list_roots",
    "drive_list_children",
    "drive_sync",
    "drive_search",
    "drive_read",
    "drive_preview",
    "drive_export",
    "file.localize",
    "file.localize_status",
    "file.localize_retry",
    "file.localize_cancel",
    "file.reconcile",
    "drive_index",
    "drive_mark_indexed",
    "drive_write",
    "drive_upload_session.start",
    "drive_upload_session.status",
    "drive_upload_session.chunk",
    "drive_upload_session.cancel",
    "drive_rename",
    "drive_move",
    "drive_trash",
    "references.manifest",
    "references.search",
    "references.resolve",
    "references.summarize",
    "health.check",
]

STORAGE_ACTION_ALIASES = {
    "write": "file.content.write",
    "write-file": "file.content.write",
    "write-content": "file.content.write",
    "read_file": "file.content.read",
    "read_text": "file.text.read",
    "image.compose_side_by_side": "image.compose_pair",
}


def operations_manifest_payload() -> dict[str, Any]:
    """Return the compact agent-facing contract for Storage operations."""
    return {
        "app_id": "storage",
        "schema_version": "1",
        "default_action": "operations.manifest",
        "commands": [
            {
                "surface": "cli",
                "name": "storage",
                "description": "Inspect, search, preview, read, write, move, and delete workspace Storage files.",
            }
        ],
        "tools": [
            {
                "surface": "mcp",
                "name": "maverick_storage",
                "description": "Generic Storage operation runner for less common actions.",
            },
            {"surface": "mcp", "name": "storage_list_files", "operation": "catalog"},
            {"surface": "mcp", "name": "storage_file_info", "operation": "file_info"},
            {"surface": "mcp", "name": "storage_read_file", "operation": "file.content.read"},
            {"surface": "mcp", "name": "storage_read_text", "operation": "file.text.read"},
            {"surface": "mcp", "name": "storage_preview_text", "operation": "file.preview.text"},
            {"surface": "mcp", "name": "storage_preview_table", "operation": "file.preview.table"},
            {"surface": "mcp", "name": "storage_write_file", "operation": "file.content.write"},
            {"surface": "mcp", "name": "storage_update_markdown_file", "operation": "update_markdown_file"},
            {"surface": "mcp", "name": "storage_image_inspect", "operation": "image.inspect"},
            {"surface": "mcp", "name": "storage_image_compose_pair", "operation": "image.compose_pair"},
            {"surface": "mcp", "name": "storage_drive_list_roots", "operation": "drive_list_roots"},
            {"surface": "mcp", "name": "storage_drive_list_children", "operation": "drive_list_children"},
            {"surface": "mcp", "name": "storage_drive_search", "operation": "drive_search"},
            {"surface": "mcp", "name": "storage_drive_read", "operation": "drive_read"},
            {"surface": "mcp", "name": "storage_drive_preview", "operation": "drive_preview"},
            {"surface": "mcp", "name": "storage_drive_export", "operation": "drive_export"},
            {"surface": "mcp", "name": "storage_file_localize", "operation": "file.localize", "tool_profile": "remote_localization"},
            {"surface": "mcp", "name": "storage_file_localize_status", "operation": "file.localize_status", "tool_profile": "remote_localization"},
            {"surface": "mcp", "name": "storage_file_localize_retry", "operation": "file.localize_retry", "tool_profile": "remote_localization"},
            {"surface": "mcp", "name": "storage_file_localize_cancel", "operation": "file.localize_cancel", "tool_profile": "remote_localization"},
            {"surface": "mcp", "name": "storage_file_reconcile", "operation": "file.reconcile"},
            {"surface": "mcp", "name": "storage_drive_index", "operation": "drive_index"},
            {"surface": "mcp", "name": "storage_drive_mark_indexed", "operation": "drive_mark_indexed"},
            {"surface": "mcp", "name": "storage_drive_write", "operation": "drive_write", "tool_profile": "remote_write"},
            {"surface": "mcp", "name": "storage_drive_rename", "operation": "drive_rename", "tool_profile": "remote_write"},
            {"surface": "mcp", "name": "storage_drive_move", "operation": "drive_move", "tool_profile": "remote_write"},
            {"surface": "mcp", "name": "storage_drive_trash", "operation": "drive_trash", "tool_profile": "remote_delete"},
            {"surface": "mcp", "name": "storage_reference_search", "operation": "references.search"},
            {"surface": "mcp", "name": "storage_reference_resolve", "operation": "references.resolve"},
            {"surface": "mcp", "name": "storage_reference_summarize", "operation": "references.summarize"},
        ],
        "recommended": [
            {
                "task": "list_workspace_files",
                "operation": "catalog",
                "calls_required": 1,
                "example": {"action": "catalog", "limit": 20},
            },
            {
                "task": "read_one_file",
                "operation": "file.content.read",
                "calls_required": 1,
                "example": {"action": "file.content.read", "workspace_relative_path": "storage/generated/report.md"},
            },
            {
                "task": "read_one_file_without_inline_bytes",
                "operation": "file.content.read",
                "calls_required": 1,
                "example": {
                    "action": "file.content.read",
                    "workspace_relative_path": "storage/generated/report.pdf",
                    "return_handle": True,
                },
            },
            {
                "task": "read_one_text_document",
                "operation": "file.text.read",
                "calls_required": 1,
                "example": {"action": "file.text.read", "workspace_relative_path": "storage/generated/report.md"},
            },
            {
                "task": "create_or_overwrite_generated_file",
                "operation": "file.content.write",
                "calls_required": 1,
                "example": {
                    "action": "file.content.write",
                    "workspace_relative_path": "storage/generated/report.md",
                    "mode": "overwrite",
                    "confirm": True,
                    "content": "# Report",
                },
            },
            {
                "task": "update_markdown_without_full_rewrite",
                "operation": "update_markdown_file",
                "calls_required": 1,
                "example": {
                    "action": "update_markdown_file",
                    "workspace_relative_path": "storage/generated/report.md",
                    "expected_sha256": "<sha256 from file_info or read_text>",
                    "replacements": [{"old_text": "Status: draft", "new_text": "Status: final"}],
                },
            },
            {
                "task": "combine_front_back_images",
                "operation": "image.compose_pair",
                "calls_required": 1,
                "example": {
                    "action": "image.compose_pair",
                    "images": [
                        "storage/generated/mail/attachments/id-front.jpg",
                        "storage/generated/mail/attachments/id-back.jpg",
                    ],
                    "target_folder": "image-ops",
                    "file_name": "id-card.jpg",
                    "mode": "versioned",
                },
            },
        ],
        "operations": [
            {
                "action": "catalog",
                "aliases": ["file.catalog.list"],
                "description": "List files and folders from the workspace Storage inventory.",
                "optional": [
                    "query",
                    "role",
                    "kind",
                    "folder_path",
                    "file_ids",
                    "workspace_relative_paths",
                    "offset",
                    "limit",
                    "known_revision",
                ],
                "payload_profile": "paginated_metadata",
            },
            {
                "action": "file_info",
                "description": "Return metadata for one file by role/path or workspace_relative_path.",
                "required_any": ["workspace_relative_path", "role + relative_path"],
                "payload_profile": "single_record_metadata",
            },
            {
                "action": "file.content.read",
                "aliases": ["read_file"],
                "description": "Read one file as bounded base64 content, or return a Storage file handle without inline bytes.",
                "required_any": ["workspace_relative_path", "role + relative_path"],
                "optional": ["max_bytes", "return_handle", "include_content"],
                "payload_profile": "explicit_content",
            },
            {
                "action": "file.text.read",
                "aliases": ["read_text"],
                "description": "Extract one transport-safe text page for a supported Storage document; continue with next_offset while has_more is true.",
                "required_any": ["workspace_relative_path", "role + relative_path"],
                "optional": ["offset", "max_chars"],
                "payload_profile": "explicit_text_content",
            },
            {
                "action": "update_markdown_file",
                "description": "Atomically replace Markdown content or apply exact replacements guarded by expected_sha256.",
                "required_any": ["workspace_relative_path", "role + relative_path"],
                "required_one_of": ["content", "replacements + expected_sha256"],
                "payload_profile": "guarded_markdown_write_result",
            },
            {
                "action": "file.content.write",
                "aliases": ["write", "write_file", "write-file", "write-content"],
                "description": "Create, overwrite, upsert, or write a versioned small workspace Storage file inline.",
                "required_any": ["workspace_relative_path", "role + relative_path"],
                "required_one_of": ["content", "content_base64"],
                "optional": ["mode"],
                "payload_profile": "single_write_result",
            },
            {
                "action": "image.inspect",
                "description": "Read image dimensions, display orientation, size, and SHA-256 for local Storage images.",
                "required_any": ["images", "workspace_relative_paths", "workspace_relative_path"],
                "payload_profile": "image_metadata",
            },
            {
                "action": "image.compose_pair",
                "aliases": ["image.compose_side_by_side"],
                "description": "Auto-rotate and compose two local Storage images side by side into storage/generated.",
                "required": ["images"],
                "optional": [
                    "target_folder",
                    "file_name",
                    "target_workspace_relative_path",
                    "output_format",
                    "height",
                    "mode",
                    "confirm",
                ],
                "payload_profile": "single_generated_image",
            },
            {
                "action": "local_upload_session.start",
                "description": "Start a chunked local Storage upload for files that exceed the inline base64 write path.",
                "required": ["role", "file_name", "size_bytes"],
                "optional": ["folder_relative_path", "content_type", "mode"],
                "payload_profile": "local_upload_session",
            },
            {
                "action": "local_upload_session.chunk",
                "description": "Append one bounded base64 chunk to a local Storage upload session.",
                "required": ["local_upload_session_id", "chunk_offset", "content_base64"],
                "payload_profile": "local_upload_session",
            },
            {
                "action": "local_upload_session.status",
                "description": "Read one local Storage upload session status.",
                "required": ["local_upload_session_id"],
                "payload_profile": "local_upload_session",
            },
            {
                "action": "local_upload_session.cancel",
                "description": "Cancel one local Storage upload session and remove incomplete bytes.",
                "required": ["local_upload_session_id"],
                "payload_profile": "local_upload_session",
            },
            {
                "action": "preview_text",
                "aliases": ["file.preview.text"],
                "description": "Extract a bounded text preview for supported files.",
                "required_any": ["workspace_relative_path", "role + relative_path"],
                "optional": ["max_chars"],
                "payload_profile": "bounded_preview",
            },
            {
                "action": "preview_table",
                "aliases": ["file.preview.table"],
                "description": "Extract bounded table data for CSV and spreadsheet files.",
                "required_any": ["workspace_relative_path", "role + relative_path"],
                "optional": ["max_rows", "max_columns"],
                "payload_profile": "bounded_table_preview",
            },
            {
                "action": "references.search",
                "description": "Search Storage file or folder app references.",
                "optional": ["query", "entity_type", "limit"],
                "payload_profile": "compact_references",
            },
            {
                "action": "references.resolve",
                "description": "Resolve one Storage file or folder app reference.",
                "required": ["entity_id"],
                "optional": ["entity_type"],
                "payload_profile": "single_reference",
            },
            {
                "action": "references.summarize",
                "description": "Summarize one Storage file or folder app reference.",
                "required": ["entity_id"],
                "optional": ["entity_type"],
                "payload_profile": "single_reference_summary",
            },
            {
                "action": "drive_list_roots",
                "description": "List Google Drive roots for one Storage-owned Drive connection.",
                "required": ["connection_id"],
                "optional": ["limit", "page_token"],
                "payload_profile": "remote_provider_metadata",
            },
            {
                "action": "drive_list_children",
                "description": "List children under one Drive parent id and normalize them as Storage files and folders.",
                "required": ["connection_id"],
                "required_any": ["parent_drive_file_id", "drive_file_id"],
                "optional": ["limit", "page_token"],
                "payload_profile": "remote_provider_metadata",
            },
            {
                "action": "drive_search",
                "description": "Run a bounded Google Drive search through Storage and return stable Storage file ids.",
                "required": ["connection_id"],
                "optional": ["query", "parent_drive_file_id", "limit"],
                "payload_profile": "remote_provider_metadata",
            },
            {
                "action": "drive_read",
                "description": "Read bounded bytes from one Google Drive file through Storage without exposing Google tokens.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "optional": ["max_bytes"],
                "payload_profile": "remote_bounded_content",
            },
            {
                "action": "drive_preview",
                "description": "Return a bounded Drive preview. Storage downloads binary files and centrally exports Google Docs, Sheets, and Slides to readable text.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "optional": ["max_bytes", "max_chars"],
                "payload_profile": "remote_bounded_preview",
            },
            {
                "action": "drive_export",
                "description": "Export Google Docs, Sheets, and Slides through Drive files.export with Storage-owned format selection and the Google 10 MB export limit.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "optional": ["export_mime_type", "max_bytes"],
                "payload_profile": "remote_bounded_content",
            },
            {
                "action": "file.localize",
                "description": "Download one browser-streamable Drive image, video, audio, or PDF into Storage's workspace-governed local cache for later Range streaming without exposing Google tokens.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "optional": ["max_bytes", "force"],
                "payload_profile": "remote_localization",
            },
            {
                "action": "file.localize_status",
                "description": "Return current Drive localization status, progress, retry/cancel availability, and stream URL metadata.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "payload_profile": "remote_localization",
            },
            {
                "action": "file.localize_retry",
                "description": "Retry Drive localization for a failed or canceled browser-streamable file.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "optional": ["max_bytes"],
                "payload_profile": "remote_localization",
            },
            {
                "action": "file.localize_cancel",
                "description": "Cancel a pending Drive localization and remove incomplete local cache bytes.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "payload_profile": "remote_localization",
            },
            {
                "action": "file.reconcile",
                "description": "Reconcile Storage inventory with local filesystem changes or refresh one known Drive file record.",
                "optional": ["stable_storage_file_id", "connection_id + drive_file_id", "folder_path", "limit"],
                "payload_profile": "reconciled_metadata",
            },
            {
                "action": "drive_index",
                "description": "Prepare a bounded Memory ingestion payload for one Google Drive file using Storage preview/export and a stable Storage reference.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "optional": ["max_bytes", "max_chars <= 20000"],
                "payload_profile": "remote_memory_source",
            },
            {
                "action": "drive_mark_indexed",
                "description": "Mark one Drive Storage reference indexed after Memory ingest succeeds. This is the post-ingest acknowledgement for agent orchestration.",
                "required": ["stable_storage_file_id"],
                "optional": ["source_version", "memory_node_id", "memory_external_ref_id", "memory_source_version_id"],
                "payload_profile": "remote_index_ack",
            },
            {
                "action": "drive_write",
                "description": "Upload a new Drive file into a folder or update binary Drive file content where the Drive API allows it. Requires Drive write capabilities and emits an audit event.",
                "required_any": ["connection_id + parent_drive_file_id + file_name", "connection_id + drive_file_id", "stable_storage_file_id"],
                "required_one_of": ["content", "content_base64"],
                "optional": ["content_type"],
                "payload_profile": "remote_write_result",
            },
            {
                "action": "drive_upload_session.start",
                "description": "Start a Storage-owned Google Drive resumable upload session for large files.",
                "required": ["connection_id", "parent_drive_file_id", "file_name", "size_bytes"],
                "optional": ["content_type"],
                "payload_profile": "remote_upload_session",
            },
            {
                "action": "drive_upload_session.status",
                "description": "Return current Storage-owned Drive upload session progress.",
                "required": ["drive_upload_session_id"],
                "optional": ["refresh_remote", "connection_id"],
                "payload_profile": "remote_upload_session",
            },
            {
                "action": "drive_upload_session.chunk",
                "description": "Upload one base64-encoded chunk into a Storage-owned Drive resumable upload session.",
                "required": ["drive_upload_session_id", "chunk_offset", "content_base64"],
                "payload_profile": "remote_upload_session",
            },
            {
                "action": "drive_upload_session.cancel",
                "description": "Cancel a Storage-owned Drive resumable upload session.",
                "required": ["drive_upload_session_id"],
                "payload_profile": "remote_upload_session",
            },
            {
                "action": "drive_rename",
                "description": "Rename one Google Drive file after capability checks. Emits an audit event.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "required": ["new_name"],
                "payload_profile": "remote_write_result",
            },
            {
                "action": "drive_move",
                "description": "Move one Google Drive file to a target Drive folder after source and target capability checks. Emits an audit event.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "required": ["target_parent_drive_file_id"],
                "payload_profile": "remote_write_result",
            },
            {
                "action": "drive_trash",
                "description": "Trash one Google Drive file after delete capability checks. Requires confirm=true or explicit delete_policy and emits an audit event.",
                "required_any": ["connection_id + drive_file_id", "stable_storage_file_id"],
                "required_any_policy": ["confirm=true", "delete_policy"],
                "payload_profile": "remote_delete_result",
            },
        ],
        "payload_profiles": {
            "operations.manifest": "compact_default",
            "catalog": "explicit_action_paginated",
            "file.catalog.list": "explicit_action_paginated",
            "file_info": "metadata_only",
            "file.content.read": "explicit_file_content_only",
            "file.text.read": "explicit_text_content",
            "preview_text": "bounded_preview_only",
            "file.preview.text": "bounded_preview_only",
            "preview_table": "bounded_table_preview_only",
            "file.preview.table": "bounded_table_preview_only",
            "references.search": "compact_results",
            "references.resolve": "single_reference",
            "references.summarize": "single_reference_summary",
            "drive_list_roots": "remote_provider_metadata",
            "drive_list_children": "remote_provider_metadata",
            "drive_search": "remote_provider_metadata",
            "drive_read": "remote_bounded_content",
            "drive_preview": "remote_bounded_preview",
            "drive_export": "remote_bounded_content",
            "file.localize": "remote_localization",
            "file.localize_status": "remote_localization",
            "file.localize_retry": "remote_localization",
            "file.localize_cancel": "remote_localization",
            "file.reconcile": "reconciled_metadata",
            "drive_index": "remote_memory_source",
            "drive_mark_indexed": "remote_index_ack",
            "drive_write": "remote_write_result",
            "drive_upload_session.start": "remote_upload_session",
            "drive_upload_session.status": "remote_upload_session",
            "drive_upload_session.chunk": "remote_upload_session",
            "drive_upload_session.cancel": "remote_upload_session",
            "drive_rename": "remote_write_result",
            "drive_move": "remote_write_result",
            "drive_trash": "remote_delete_result",
        },
        "payload_profile_details": {
            "explicit_text_content": {
                "returns": [
                    "text",
                    "text_char_count",
                    "offset",
                    "range_end",
                    "has_more",
                    "next_offset",
                    "complete",
                    "no preview character cap",
                ],
            },
            "remote_memory_source": {
                "returns": [
                    "status=ready_for_memory",
                    "source_version",
                    "preview_text <= 20000 chars",
                    "preview_truncated",
                    "Storage text extraction for supported binary Office Drive files when Drive preview has no preview_text",
                    "memory_source.source_kind=remote_storage_file",
                    "memory_source.metadata.stable_storage_file_id",
                    "does not mark indexed until drive_mark_indexed",
                ],
            },
            "remote_localization": {
                "returns": [
                    "status=ready",
                    "localization.id",
                    "localization.progress",
                    "localization.sha256",
                    "stream_url",
                    "download_url",
                    "local cache hit status",
                ],
            },
            "remote_index_ack": {
                "returns": ["status=indexed", "stable_storage_file_id", "source_version", "memory ack ids when provided", "file.index_status=indexed"],
            },
        },
        "aliases": STORAGE_ACTION_ALIASES,
        "id_patterns": {
            "file_id": "file_<uuid>",
            "folder_id": "<role>:<percent-encoded-relative-path>/",
            "workspace_relative_path": "storage/(uploaded|generated)/<relative-path>",
            "google_drive_file": "stable_storage_file_id file_<hash> or connection_id + drive_file_id",
        },
        "policy": {
            "sandbox_agent_allowed": True,
            "requires_workspace_context": True,
            "requires_full_access": False,
            "remote_drive": {
                "read_tools": ["drive_list_roots", "drive_list_children", "drive_search", "drive_read", "drive_preview", "drive_export", "file.localize", "file.localize_status", "file.reconcile", "drive_index", "drive_mark_indexed"],
                "write_tools": ["drive_write", "drive_upload_session.start", "drive_upload_session.chunk", "drive_upload_session.cancel", "file.localize_retry", "file.localize_cancel", "drive_rename", "drive_move"],
                "delete_tools": ["drive_trash"],
                "delete_requires": ["confirm=true", "delete_policy"],
            },
        },
    }
