server {
    listen 80;
    listen [::]:80;
    server_name *.sidecars.{{HOSTNAME}};

    location ^~ /.well-known/acme-challenge/ {
        root {{BROWSER_ORIGIN_ACME_WEBROOT}};
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
