"""Public app contract facade."""

from core.apps.contract_builders import (
    build_app_capabilities,
    build_app_compatibility,
    build_app_contract,
    build_app_distribution,
    build_app_entrypoints,
    build_app_failure_semantics,
    build_app_health_contract,
    build_app_hook_timeouts,
    build_app_lifecycle,
    build_app_permissions,
    build_app_rollback_support,
    build_app_storage,
    build_parsed_app_contract,
    build_provided_interface_declaration,
    build_reference_entity_declaration,
    build_required_interface_declaration,
    build_view_state_action_declaration,
    build_view_surface_declaration,
    build_widget_actions,
    build_widget_declaration,
    build_widget_frontend,
)
from core.apps.contract_common import (
    APP_CONTRACT_FILENAME,
    APP_ID_PATTERN,
    CURRENT_APP_CONTRACT_VERSION,
    _normalize_slug,
    app_contract_path,
    utcnow,
)
from core.apps.contract_parser import parse_app_contract_file
from core.apps.contract_records import parsed_contract_to_app_source_record, parsed_contract_to_workspace_local_project_record
from core.apps.contract_serializer import app_contract_payload, write_app_contract_file

__all__ = [
    "APP_CONTRACT_FILENAME",
    "APP_ID_PATTERN",
    "CURRENT_APP_CONTRACT_VERSION",
    "_normalize_slug",
    "app_contract_path",
    "app_contract_payload",
    "build_app_capabilities",
    "build_app_compatibility",
    "build_app_contract",
    "build_app_distribution",
    "build_app_entrypoints",
    "build_app_failure_semantics",
    "build_app_health_contract",
    "build_app_hook_timeouts",
    "build_app_lifecycle",
    "build_app_permissions",
    "build_app_rollback_support",
    "build_app_storage",
    "build_parsed_app_contract",
    "build_provided_interface_declaration",
    "build_reference_entity_declaration",
    "build_required_interface_declaration",
    "build_view_state_action_declaration",
    "build_view_surface_declaration",
    "build_widget_actions",
    "build_widget_declaration",
    "build_widget_frontend",
    "parse_app_contract_file",
    "parsed_contract_to_app_source_record",
    "parsed_contract_to_workspace_local_project_record",
    "utcnow",
    "write_app_contract_file",
]
