import { expect, test } from '@playwright/test';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { backend, mount } from './backend_fixture';

let dataRoot: string;
const providers = { calendar: 'calendar', files: 'storage', 'file-write': 'storage', tasks: 'checklist', speech: 'speech', mail: 'mail' };
test.beforeEach(() => { dataRoot = mkdtempSync(`${tmpdir()}/crm-integrations-e2e-`); });
test.afterEach(() => { rmSync(dataRoot, { recursive: true, force: true }); });

test('meeting proposal needs approval, executes once, resolves and refreshes the real Calendar reference', async ({ page }, testInfo) => {
  await mount(page, dataRoot, providers);
  await page.locator('tbody tr').filter({ hasText: 'Ada Example' }).click();
  const connected = page.locator('.vn-integrations');
  await expect(connected.getByRole('heading', { name: 'Connected work' })).toBeVisible();
  await connected.getByText('Prepare an app action', { exact: true }).click();
  await connected.getByLabel('Action', { exact: true }).selectOption('calendar_event');
  await connected.getByLabel('Title', { exact: true }).fill('Relationship review');
  await connected.getByLabel('Starts (your local time)').fill('2030-10-01T09:00');
  await connected.getByLabel('Ends (your local time)').fill('2030-10-01T10:00');
  await connected.getByRole('button', { name: 'Prepare proposal', exact: true }).click();
  const journal = () => backend(dataRoot, { action: 'crm.integration_list', entity_type: 'contact', entity_id: 'contact_ada' }).body;
  await expect(connected.getByRole('button', { name: 'Approve proposal', exact: true })).toBeVisible();
  expect(journal().operations[0].status).toBe('prepared');
  await expect(connected.getByRole('button', { name: 'Execute approved action' })).toHaveCount(0);
  await connected.getByRole('button', { name: 'Approve proposal', exact: true }).click();
  await connected.getByRole('button', { name: 'Execute approved action' }).click();
  await expect(connected.getByText('succeeded · applied', { exact: true })).toBeVisible();
  expect(journal().operations[0].attempts).toBe(1);
  await connected.getByText('Find and connect app records', { exact: true }).click();
  await connected.getByLabel('Search provider', { exact: true }).selectOption('calendar');
  await connected.getByLabel('Search linked context').fill('Relationship review');
  await connected.getByRole('button', { name: 'Search provider', exact: true }).click();
  await connected.getByRole('button', { name: 'Connect', exact: true }).click();
  await connected.getByRole('button', { name: 'Refresh linked records' }).click();
  await expect(connected.getByRole('button', { name: 'Refresh linked records' })).toBeEnabled();
  const exported = backend(dataRoot, { action: 'crm.export' }).body.export;
  expect(exported.external_refs).toHaveLength(1);
  expect(exported.external_refs[0].metadata.last_error).toBe('');
  expect(exported.external_refs[0].metadata.last_synced_at).toBeTruthy();
  await page.screenshot({ path: testInfo.outputPath('crm-connected-work-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('crm-connected-work-mobile.png'), fullPage: true });
});

test('creates a linked Storage brief and records meeting follow-ups as separate reviewable proposals', async ({ page }) => {
  await mount(page, dataRoot, providers);
  await page.locator('tbody tr').filter({ hasText: 'Ada Example' }).click();
  const connected = page.locator('.vn-integrations');
  await connected.getByText('Prepare an app action', { exact: true }).click();
  await connected.getByLabel('Action', { exact: true }).selectOption('document');
  await connected.getByRole('button', { name: 'Use CRM meeting brief' }).click();
  await expect(connected.getByLabel('Markdown document')).toHaveValue(/Ada Example/);
  await connected.getByRole('button', { name: 'Prepare proposal', exact: true }).click();
  await connected.getByRole('button', { name: 'Approve proposal', exact: true }).click();
  await connected.getByRole('button', { name: 'Execute approved action' }).click();
  await expect(connected.getByText('succeeded · applied', { exact: true })).toBeVisible();
  await connected.getByText('Meeting brief & outcome', { exact: true }).click();
  await connected.getByLabel('Outcome and decisions').fill('Customer requested a revised offer.');
  await connected.getByLabel('Proposed follow-ups (one per line)').fill('Prepare revised offer');
  await connected.getByRole('button', { name: 'Record outcome' }).click();
  await expect(connected.getByText('Prepare revised offer', { exact: true })).toBeVisible();
  expect(backend(dataRoot, { action: 'crm.export' }).body.export.tasks).toHaveLength(1);
  await connected.getByRole('button', { name: 'Approve proposal', exact: true }).click();
  await connected.getByRole('button', { name: 'Apply approved proposal' }).click();
  await expect(connected.getByRole('button', { name: 'Apply approved proposal' })).toHaveCount(0);
  const exported = backend(dataRoot, { action: 'crm.export' }).body.export;
  expect(exported.tasks).toHaveLength(2);
  expect(exported.external_refs[0].source_app_id).toBe('storage');
  expect(exported.record_links.some((link: { relationship: string }) => link.relationship === 'followup')).toBe(true);
});
