from __future__ import annotations

import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]


class BaseShellAppMountingTests(unittest.TestCase):
    def test_base_shell_apps_route_defaults_to_app_store(self) -> None:
        session_source = (REPO_ROOT / "apps/base-shell/frontend/src/session.ts").read_text()
        navigation_source = (REPO_ROOT / "apps/base-shell/frontend/src/navigation.ts").read_text()
        shell_source = (REPO_ROOT / "apps/base-shell/frontend/src/AppShell.tsx").read_text()
        sidebar_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/Sidebar.tsx").read_text()

        self.assertIn('activeAppId: "chat"', session_source)
        self.assertIn('sidebarMode: "rail"', session_source)
        self.assertNotIn('findRegistryApp(apps, "chat")', navigation_source)
        self.assertIn('APP_STORE_APP_ID = "app-store"', navigation_source)
        self.assertIn("findRegistryApp(apps, APP_STORE_APP_ID)", navigation_source)
        self.assertIn("const initialLaunchRoute = useMemo(() => initialShellLaunchRoute(initialRoute), [initialRoute]);", shell_source)
        self.assertIn("const initialActiveAppId = initialLaunchRoute.appId || initialSession.activeAppId;", shell_source)
        self.assertNotIn('window.location.pathname === "/" ? null : initialSession.activeAppId', shell_source)
        self.assertNotIn("setActiveAppId(null)", shell_source)
        self.assertIn("replaceShellAppRoute(null, {})", shell_source)
        self.assertNotIn('app.app_id === "app-store"', shell_source)
        self.assertIn('contentKind="shell.sidebar.primary"', sidebar_source)

    def test_base_shell_uses_persistent_app_frames(self) -> None:
        host_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/AppFrameHost.tsx").read_text()
        workspace_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/WorkspaceView.tsx").read_text()

        self.assertIn("maverick.app.navigate", host_source)
        self.assertIn("maverick.app.ready", host_source)
        self.assertIn("postMessage", host_source)
        self.assertIn("syncAppFrameShellLayout", host_source)
        self.assertIn("src={appFrameSrc(app.frontend_mount, revision)}", host_source)
        self.assertIn("currentShellAppRoute", (REPO_ROOT / "apps/base-shell/frontend/src/AppShell.tsx").read_text())
        self.assertIn("pushShellAppRoute", (REPO_ROOT / "apps/base-shell/frontend/src/AppShell.tsx").read_text())
        self.assertIn("replaceShellAppRoute", (REPO_ROOT / "apps/base-shell/frontend/src/AppShell.tsx").read_text())
        self.assertIn('path == "/app"', (REPO_ROOT / "core/api/platform_host.py").read_text())
        self.assertIn("connectAppEventSocket", host_source)
        self.assertIn("maverick.app.frontend-changed", host_source)
        self.assertIn("_maverick_refresh", host_source)
        self.assertNotIn("frontendDocumentSignature", host_source)
        self.assertNotIn("_maverick_probe", host_source)
        self.assertNotIn("setTimeout(probeActiveFrontend", host_source)
        self.assertNotIn("URLSearchParams", workspace_source)
        self.assertNotIn("buildAppFrameSrc", workspace_source)

    def test_base_shell_remounts_app_frames_and_widgets_by_workspace(self) -> None:
        host_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/AppFrameHost.tsx").read_text()
        sidebar_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/Sidebar.tsx").read_text()
        overlay_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/ShellOverlayWidgets.tsx").read_text()
        widget_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/WidgetSlot.tsx").read_text()

        self.assertIn("activeMountKey = `${activeWorkspaceId}:${activeApp.app_id}`", host_source)
        self.assertIn("mountKey: activeMountKey", host_source)
        self.assertIn("key={`${mountKey}:${revision}`}", host_source)
        iframe_policy_source = (REPO_ROOT / "apps/base-shell/frontend/src/iframePolicy.ts").read_text()
        self.assertIn('MAVERICK_IFRAME_SANDBOX = "allow-downloads allow-forms allow-popups allow-same-origin allow-scripts"', iframe_policy_source)
        self.assertIn("sandbox={MAVERICK_IFRAME_SANDBOX}", host_source)
        self.assertIn("sandbox={MAVERICK_IFRAME_SANDBOX}", widget_source)
        self.assertIn("postToMaverickFrame", host_source)
        self.assertIn("postToMaverickFrame", widget_source)
        self.assertIn("postMaverickFrameVisibility", iframe_policy_source)
        self.assertIn("maverick.app.visibility-changed", iframe_policy_source)
        self.assertIn("visible: app.app_id === activeApp.app_id", host_source)
        self.assertIn("postMaverickFrameVisibility(event.currentTarget", host_source)
        self.assertIn("postWidgetVisibility()", widget_source)
        self.assertIn('postMessage(message, "*")', iframe_policy_source)
        self.assertIn("activeWorkspaceId={activeWorkspaceId}", sidebar_source)
        self.assertIn("activeWorkspaceId={activeWorkspaceId}", overlay_source)
        self.assertIn("activeWorkspaceId: string", widget_source)
        self.assertIn("message_id: `${activeWorkspaceId}:${hostAppId}:${contentKind}`", widget_source)
        self.assertIn("workspace_id: activeWorkspaceId", widget_source)
        self.assertIn("key={`${activeWorkspaceId}:${widget.owner_app_id}:${widget.widget_id}:${contextToken}:${frameRevision}`}", widget_source)
        self.assertIn("url.hash = `context=${encodeURIComponent(contextToken)}`", widget_source)
        self.assertIn("maverick.widget.resize", widget_source)
        self.assertIn("maverick.widget.context-changed", widget_source)
        self.assertIn("onLoad={postWidgetContextChanged}", widget_source)
        self.assertIn("navigation_scope: typeof payload.navigation_scope", widget_source)
        self.assertIn('size === "overlay"', widget_source)
        self.assertIn('size === "overlay" && activeAppId && activeAppId === widget.owner_app_id', widget_source)
        self.assertNotIn("}, [activeWorkspaceId, contentSignature, contentKind, hostAppId])", widget_source)
        shell_styles = (REPO_ROOT / "apps/base-shell/frontend/src/styles/layout.css").read_text()
        self.assertIn("width: 100vw", shell_styles)
        self.assertIn("position: absolute", shell_styles)
        self.assertIn("right: 0", shell_styles)
        self.assertIn("bottom: 0", shell_styles)
        self.assertIn("flex: none", shell_styles)
        self.assertIn("max-width: 100vw", shell_styles)
        self.assertIn("max-height: min(38rem, calc(100dvh - 2rem))", shell_styles)
        self.assertNotIn("width: min(23rem, calc(100vw - 1.4rem))", shell_styles)
        self.assertNotIn(".bs-widget-slot--overlay.is-collapsed", shell_styles)
        self.assertNotIn(".bs-widget-slot--overlay .bs-widget-slot__frame", shell_styles)

    def test_base_shell_caches_resolved_app_dependencies(self) -> None:
        host_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/AppFrameHost.tsx").read_text()

        self.assertIn('DEPENDENCY_CACHE_STORAGE_KEY = "maverick.baseShell.appDependencies"', host_source)
        self.assertIn("dependencyCacheKey(activeWorkspaceId, activeApp.app_id)", host_source)
        self.assertIn("loadDependencyCache()", host_source)
        self.assertIn("saveDependencyCache(next)", host_source)
        self.assertIn('payload.status === "resolved"', host_source)
        self.assertIn("delete next[cacheKey]", host_source)
        self.assertIn("const cached = dependencyCacheRef.current[activeDependencyCacheKey] || null", host_source)
        self.assertIn("if (cached) {", host_source)
        self.assertIn("postDependencies(frameRefs.current[activeApp.app_id], activeApp.app_id, cached)", host_source)
        self.assertIn("(!dependencies || dependencyError)", host_source)
        self.assertIn('DEPENDENCY_LOG_PREFIX = "[Maverick dependencies]"', host_source)
        self.assertIn('DEPENDENCY_DEBUG_STORAGE_KEY = "maverick.baseShell.debug.dependencies"', host_source)
        self.assertIn("window.localStorage.getItem(DEPENDENCY_DEBUG_STORAGE_KEY)", host_source)
        self.assertIn('logDependencySetup("cache:hit"', host_source)
        self.assertIn('logDependencySetup("cache:miss"', host_source)
        self.assertIn('logDependencySetup("fetch:start"', host_source)

    def test_base_shell_uses_registry_backed_overlay_widget(self) -> None:
        shell_source = (REPO_ROOT / "apps/base-shell/frontend/src/AppShell.tsx").read_text()
        overlay_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/ShellOverlayWidgets.tsx").read_text()

        self.assertIn("<ShellOverlayWidgets", shell_source)
        self.assertIn("activeApp={activeApp}", shell_source)
        self.assertIn("active_app", overlay_source)
        self.assertIn("activeApp.app_id", overlay_source)
        self.assertIn('hostAppId="base-shell"', overlay_source)
        self.assertIn('contentKind="shell.overlay.bottomright"', overlay_source)
        self.assertIn('size="overlay"', overlay_source)
        self.assertNotIn("chat-floating", shell_source)
        self.assertNotIn("chat-floating", overlay_source)

    def test_sidebar_uses_chat_widget_and_app_store_pinned_rail(self) -> None:
        sidebar_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/Sidebar.tsx").read_text()
        shell_source = (REPO_ROOT / "apps/base-shell/frontend/src/AppShell.tsx").read_text()
        api_source = (REPO_ROOT / "apps/base-shell/frontend/src/api.ts").read_text()
        session_source = (REPO_ROOT / "apps/base-shell/frontend/src/session.ts").read_text()
        widget_slot_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/WidgetSlot.tsx").read_text()
        sidebar_styles = (REPO_ROOT / "apps/base-shell/frontend/src/styles/sidebar.css").read_text()
        shortcut_source = (REPO_ROOT / "apps/app-store/frontend/dist/widgets/app-shortcuts/main.js").read_text()

        self.assertIn('contentKind="shell.sidebar.primary"', sidebar_source)
        self.assertNotIn('contentKind="shell.sidebar.apps"', sidebar_source)
        self.assertIn("pinnedAppIds", sidebar_source)
        self.assertIn("listPinnedApps", shell_source)
        self.assertIn("pinned_apps.list", api_source)
        self.assertIn('sidebarMode: "rail"', session_source)
        self.assertIn('size?: "compact" | "fill" | "overlay"', widget_slot_source)
        self.assertNotIn("WidgetSlotSkeleton", widget_slot_source)
        self.assertNotIn("bs-widget-slot__sidebar-skeleton", sidebar_styles)
        self.assertNotIn("bs-widget-slot__compact-skeleton", sidebar_styles)
        self.assertIn('window.parent?.postMessage({ type: "maverick.widget.open-app", app_id: appId }', shortcut_source)
        self.assertNotIn('return "New Chat"', shortcut_source)
        self.assertNotIn("new_chat: true", shortcut_source)
        self.assertNotIn("new_chat_request_id", shortcut_source)

    def test_settings_shortcut_opens_settings_app_without_shell_modal(self) -> None:
        shell_source = (REPO_ROOT / "apps/base-shell/frontend/src/AppShell.tsx").read_text()
        navigation_source = (REPO_ROOT / "apps/base-shell/frontend/src/navigation.ts").read_text()
        sidebar_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/Sidebar.tsx").read_text()
        rail_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/SidebarAppRail.tsx").read_text()
        api_source = (REPO_ROOT / "apps/base-shell/frontend/src/api.ts").read_text()

        self.assertFalse((REPO_ROOT / "apps/base-shell/frontend/src/components/ShellDialogs.tsx").exists())
        self.assertIn('SETTINGS_APP_ID = "settings"', navigation_source)
        self.assertIn("app.app_id !== SETTINGS_APP_ID", navigation_source)
        self.assertIn("function openSettingsApp()", shell_source)
        self.assertIn("openApp(SETTINGS_APP_ID)", shell_source)
        self.assertIn("onOpenSettings={openSettingsApp}", shell_source)
        self.assertIn("settingsApp={settingsApp}", sidebar_source)
        self.assertIn("aria-current={activeAppId === SETTINGS_APP_ID ? \"page\" : undefined}", rail_source)
        self.assertIn("aria-label={settingsApp.name}", rail_source)
        self.assertNotIn("ShellDialogs", shell_source)
        self.assertNotIn("activeDialog", shell_source)
        self.assertNotIn("clearRuntimeSessions", shell_source)
        self.assertNotIn("clearRuntimeSessions", api_source)

    def test_workspace_create_button_is_admin_only_in_shell(self) -> None:
        sidebar_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/Sidebar.tsx").read_text()
        switcher_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/WorkspaceSwitcher.tsx").read_text()

        self.assertIn('canCreateWorkspace={user?.platform_role === "admin"}', sidebar_source)
        self.assertIn("canCreateWorkspace: boolean", switcher_source)
        self.assertIn("canCreateWorkspace ? (", switcher_source)

    def test_chat_sidebar_does_not_render_duplicate_new_chat_button(self) -> None:
        widget_source = (REPO_ROOT / "apps/chat/frontend/src/widgets/chat-sidebar/main.tsx").read_text()

        self.assertNotIn('className="bs-sidebar__nav-button"', widget_source)
        self.assertNotIn('<span className="bs-sidebar__nav-title">New chat</span>', widget_source)

    def test_chat_accepts_shell_navigation_without_url_reload(self) -> None:
        chat_source = (REPO_ROOT / "apps/chat/frontend/src/App.tsx").read_text()

        self.assertIn("maverick.app.navigate", chat_source)
        self.assertIn("maverick.app.ready", chat_source)
        self.assertIn("handleNavigationParams", chat_source)
        self.assertIn("normalizeChatRouteParams", chat_source)
        self.assertIn('kind === "threads"', chat_source)
        self.assertIn('kind === "runtime-sessions"', chat_source)
        self.assertIn("window.addEventListener(\"message\"", chat_source)
        self.assertIn("useRuntimeThreads", chat_source)
        self.assertIn("selectThreadWithoutHttp", chat_source)
        self.assertIn("consumeNewChatRequest", chat_source)
        self.assertIn("new_chat_request_id", chat_source)
        self.assertIn("suppressedExternalThreadIdRef", chat_source)
        self.assertIn("suppressedExternalThreadIdRef.current = threadId || activeThread?.thread_id || null", chat_source)
        self.assertIn("THREAD_SYNC_DEBUG_STORAGE_KEY", chat_source)
        self.assertIn('debugThreadSync("app-navigation"', chat_source)
        self.assertIn('debugThreadSync("app-notify-active-thread"', chat_source)
        self.assertNotIn("activeTurnThreadAvailability", chat_source)
        self.assertNotIn('"maverick.chat.thread-availability-changed"', chat_source)
        self.assertNotIn("availabilitySyncRequestRef", chat_source)
        self.assertNotIn("updateThread({ thread_id: currentThreadId, availability", chat_source)
        self.assertIn("const firstThread = requestedThreadId", chat_source)
        self.assertNotIn('threadPayload.threads.find((thread) => thread.thread_id === requestedThreadId) || threadPayload.threads[0]', chat_source)
        self.assertNotIn("getAgentsCommonPrompt", chat_source)
        self.assertIn("system_prompt: systemPrompt", chat_source)

    def test_chat_first_send_creates_runtime_session_with_initial_turn(self) -> None:
        chat_source = (REPO_ROOT / "apps/chat/frontend/src/App.tsx").read_text()

        submit_start = chat_source.index("async function submitMessage")
        submit_end = chat_source.index("useEffect(() => {", submit_start)
        submit_source = chat_source[submit_start:submit_end]

        self.assertIn("response = await createRuntimeSessionWithTurn({", submit_source)
        self.assertIn("project_id: draftChat?.projectId ?? null", submit_source)
        self.assertIn("inputText: message.content", submit_source)
        self.assertIn("response = await sendRuntimeTurn(", submit_source)
        self.assertIn("if (!thread.runtime_session_id)", chat_source)
        self.assertIn('throw new Error("This chat does not have a runtime session.")', chat_source)
        self.assertIn("getWidgetContext", chat_source)
        self.assertIn("activeAppContextFromWidgetContext", chat_source)
        self.assertIn('payload.type === "maverick.widget.context-changed"', chat_source)
        self.assertIn("mergeAppReferences(appReferencesFromText(input, composerMentionItems), activeAppContext)", chat_source)
        self.assertIn("QUEUED_MESSAGES_STORAGE_PREFIX", chat_source)
        self.assertIn("readPersistedQueuedMessages", chat_source)
        self.assertIn("persistQueuedMessages", chat_source)
        self.assertIn("queueStorageKey(navigationScope, activeThread?.thread_id || null)", chat_source)
        self.assertIn("useRuntimeEvents", chat_source)
        self.assertIn("onRuntimeSnapshot: () => {", chat_source)
        self.assertIn("setHasLoadedHistory(true)", chat_source)
        self.assertIn("setIsHistoryLoading(false)", chat_source)
        self.assertNotIn("RUNTIME_HISTORY_CACHE_STORAGE_PREFIX", chat_source)
        self.assertNotIn("readRuntimeHistoryCache", chat_source)
        self.assertNotIn("persistRuntimeHistoryCache", chat_source)
        self.assertNotIn("sanitizeRuntimeEventsForCache", chat_source)
        self.assertIn("activeRuntimeSessionIdRef", chat_source)
        self.assertNotIn("window.confirm", chat_source)
        self.assertIn("handleUnavailableRuntimeSession", chat_source)
        self.assertIn("deleteStoredRuntimeTranscript(runtimeSessionId)", chat_source)

    def test_chat_sidebar_settings_panel_escapes_scroll_clipping(self) -> None:
        widget_source = (REPO_ROOT / "apps/chat/frontend/src/widgets/chat-sidebar/main.tsx").read_text()
        widget_styles = (REPO_ROOT / "apps/chat/frontend/src/widgets/chat-sidebar/styles.css").read_text()

        self.assertIn("editingProjectRef", widget_source)
        self.assertIn('document.addEventListener("pointerdown", cancelProjectEditFromOutside)', widget_source)
        self.assertIn('className="bs-chat-folder__title-input-frame"', widget_source)
        self.assertIn('className="bs-chat-folder__title-input"', widget_source)
        self.assertIn('aria-label={`Rename project ${section.title}`}', widget_source)
        self.assertIn(".bs-chat-folder.is-project-editing .bs-chat-folder__header", widget_styles)
        self.assertIn(".bs-chat-folder__title-input-frame", widget_styles)
        self.assertIn("--chat-sidebar-project-edit-scale", widget_styles)

    def test_chat_floating_widget_uses_chat_owned_surfaces(self) -> None:
        widget_source = (REPO_ROOT / "apps/chat/frontend/src/widgets/chat-floating/main.tsx").read_text()
        widget_state_source = (REPO_ROOT / "apps/chat/frontend/src/widgets/chat-floating/floatingState.ts").read_text()
        widget_styles = (REPO_ROOT / "apps/chat/frontend/src/widgets/chat-floating/styles.css").read_text()

        self.assertIn('import { App } from "../../App"', widget_source)
        self.assertIn('import "../../styles/main.css"', widget_source)
        self.assertIn('import "./styles.css"', widget_source)
        self.assertIn("maverick.widget.resize", widget_source)
        self.assertIn('widget_id: "chat-floating"', widget_source)
        self.assertIn("owner_app_id: \"chat\"", widget_source)
        self.assertIn("newChatProjectId={windowItem.draftProjectId}", widget_source)
        self.assertIn("newChatRequestId={windowItem.isDraft ? windowItem.id : null}", widget_source)
        self.assertIn("threadId={windowItem.threadId}", widget_source)
        self.assertIn("ChatFloatingMount", widget_source)
        self.assertIn("setWindowCollapsed", widget_source)
        self.assertNotIn("if (isCollapsed) {", widget_source)
        self.assertNotIn("if (windowItem.isCollapsed) {", widget_source)
        self.assertIn('chat-floating-widget-launcher ${windowItem.isCollapsed ? "" : "is-hidden"}', widget_source)
        self.assertIn('chat-floating-widget-shell ${windowItem.isCollapsed ? "is-hidden" : ""}', widget_source)
        self.assertIn("createWindow", widget_source)
        self.assertIn("WIDGET_STATE_STORAGE_KEY_PREFIX", widget_state_source)
        self.assertIn("loadWidgetStateStorageKey", widget_source)
        self.assertIn("getWidgetContext", widget_source)
        self.assertIn("workspace_id", widget_source)
        self.assertIn("readPersistedOrDefaultWindows", widget_source)
        self.assertIn("readPersistedWindows", widget_state_source)
        self.assertIn("persistWindows(storageKey, windows)", widget_source)
        self.assertIn("storage.setItem", widget_state_source)
        self.assertIn("window.localStorage.getItem", widget_source)
        self.assertIn("postWidgetSize(windows)", widget_source)
        self.assertIn("floatingWidgetSize(windows)", widget_source)
        self.assertIn("useRuntimeThreads", widget_source)
        self.assertIn("isThreadBusy", widget_source)
        self.assertIn("updateThread", widget_source)
        self.assertIn("deleteThread", widget_source)
        self.assertNotIn("getRuntimeSession", widget_source)
        self.assertNotIn("refreshExecutionMode", widget_source)
        self.assertNotIn("listProviders", widget_source)
        self.assertNotIn("selectProvider", widget_source)
        self.assertNotIn("<ProviderSelector", widget_source)
        self.assertIn("maverick.shell.capture-area.start", (REPO_ROOT / "apps/chat/frontend/src/App.tsx").read_text())
        self.assertIn("maverick.widget.capture-area.complete", (REPO_ROOT / "apps/chat/frontend/src/App.tsx").read_text())
        self.assertIn("maverick.app.navigate", widget_source)
        self.assertIn("navigation_scope: windowId", widget_source)
        self.assertIn("createDraftChat", widget_source)
        self.assertIn("reconcileWindowsWithThreads", widget_source)
        self.assertIn("closeWindow", widget_source)
        self.assertIn("const hasMultipleWindows = windows.length > 1", widget_source)
        self.assertNotIn('payload.type === "maverick.chat.thread-availability-changed"', widget_source)
        self.assertNotIn("setThreads((current) => current.map((thread) => (thread.thread_id === threadId ? { ...thread, availability } : thread)))", widget_source)
        self.assertNotIn("refreshThreadsRequestIdsByScopeRef", widget_source)
        self.assertIn("threadsRef", widget_source)
        self.assertIn("windowsRef", widget_source)
        self.assertIn('debugThreadSync("widget.data-changed"', widget_source)
        self.assertNotIn('debugThreadSync("refresh-stale"', widget_source)
        self.assertNotIn('debugThreadSync("refresh-apply-unchanged"', widget_source)
        self.assertNotIn("areWindowThreadSelectionsEqual", widget_source)
        self.assertIn("THREAD_SYNC_DEBUG_STORAGE_KEY", widget_source)
        self.assertIn("setWindowThread(windowId: string, threadId: string)", widget_source)
        self.assertIn('debugThreadSync("create-draft-chat"', widget_source)
        self.assertIn('debugThreadSync("select-thread"', widget_source)
        self.assertIn("if (!navigationScope) {", widget_state_source)
        self.assertIn("threadIds.has(windowItem.threadId) ? windowItem : { ...windowItem, isDraft: true }", widget_state_source)
        self.assertIn("createWindow(\"\", true, projectId)", widget_source)
        self.assertIn('aria-label="Choose chat"', widget_source)
        self.assertIn('aria-label="New chat"', widget_source)
        self.assertIn('aria-label={isActiveThreadBusy ? "Open active chat" : isActiveThreadUnread ? "Open chat with unread response" : "Open chat"}', widget_source)
        self.assertIn('aria-label="Rename chat"', widget_source)
        self.assertIn('className="chat-floating-thread-menu__icon-action is-danger"', widget_source)
        self.assertNotIn("sendRuntimeTurn", widget_source)
        self.assertNotIn("MarkdownMessage", widget_source)
        self.assertNotIn("base-shell", widget_source)
        self.assertNotIn("apps/base-shell", widget_source)
        self.assertIn(".chat-floating-widget-shell__thread-tools", widget_styles)
        self.assertIn(".chat-floating-widget-shell.is-hidden", widget_styles)
        self.assertIn(".chat-floating-widget-launcher.is-hidden", widget_styles)
        self.assertIn(".chat-floating-thread-menu__trigger", widget_styles)
        self.assertIn(".chat-floating-thread-menu__item.is-busy", widget_styles)
        self.assertIn(".chat-floating-thread-menu__item-actions", widget_styles)
        self.assertIn(".chat-floating-thread-menu__rename-input", widget_styles)
        self.assertIn(".chat-floating-thread-menu__icon-action.is-danger", widget_styles)
        self.assertIn(".bs-chat-list__glow", widget_styles)
        self.assertIn("bs-chat-glow-rotate", widget_styles)
        self.assertIn(".chat-floating-widget-stack", widget_styles)
        self.assertIn("flex-direction: row-reverse", widget_styles)
        self.assertIn(".chat-floating-widget-shell__actions", widget_styles)
        self.assertIn(".chat-floating-widget-shell__button--danger", widget_styles)
        self.assertIn(".chat-floating-widget-shell__button--close .material-symbols-rounded", widget_styles)
        self.assertIn("#cf30aa", widget_styles)
        self.assertNotIn(".chat-floating-widget-shell__body.is-split", widget_styles)
        self.assertNotIn(".chat-floating-widget-panel", widget_styles)
        self.assertIn(".chat-floating-widget-shell__body .chatapp-root", widget_styles)
        self.assertIn("height: 100%", widget_styles)
        self.assertIn(".chat-floating-widget-shell__body .chatapp-chat-panel", widget_styles)
        self.assertIn(".chat-floating-widget-shell__body .chatapp-chat-workspace", widget_styles)

    def test_chat_thread_selection_stays_in_floating_wrapper(self) -> None:
        app_source = (REPO_ROOT / "apps/chat/frontend/src/App.tsx").read_text()
        widget_source = (REPO_ROOT / "apps/chat/frontend/src/widgets/chat-floating/main.tsx").read_text()

        self.assertNotIn("ChatHeader", app_source)
        self.assertNotIn("<ChatHeader", app_source)
        self.assertNotIn("chat-floating-widget-shell__title", widget_source)
        self.assertNotIn('aria-label="Choose chat"', app_source)
        self.assertNotIn('aria-label="New chat"', app_source)
        self.assertIn('aria-label="Choose chat"', widget_source)
        self.assertIn('aria-label="New chat"', widget_source)

    def test_shell_overlay_widget_supports_area_capture_without_app_dom_access(self) -> None:
        widget_slot_source = (REPO_ROOT / "apps/base-shell/frontend/src/components/WidgetSlot.tsx").read_text()
        shell_styles = (REPO_ROOT / "apps/base-shell/frontend/src/styles/layout.css").read_text()
        attachment_menu_source = (REPO_ROOT / "apps/chat/frontend/src/components/AttachmentMenu.tsx").read_text()

        self.assertIn("maverick.shell.capture-area.start", widget_slot_source)
        self.assertIn("navigator.mediaDevices.getDisplayMedia", widget_slot_source)
        self.assertIn("maverick.widget.capture-area.complete", widget_slot_source)
        self.assertIn("new File([blob]", widget_slot_source)
        self.assertIn("bs-capture-overlay", shell_styles)
        self.assertIn("Capture page area", attachment_menu_source)
        self.assertNotIn("contentDocument", widget_slot_source)
        self.assertNotIn("contentWindow.document", widget_slot_source)


if __name__ == "__main__":
    unittest.main()
