"""Small operator-only HTTP-01 policy; no Core, app execution or secrets IPC."""
import json
import os
from pathlib import Path
import re
import stat
import time

TLS_ROOT = Path("/var/lib/maverick/external-apps-tls")
ACME_ROOT = Path("/var/lib/maverick/external-apps-acme")
PROXY = "/etc/nginx/snippets/maverick-external-apps-proxy.conf"


def read_json(path, limit=2 * 1024 * 1024):
    with os.fdopen(os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK), "rb") as handle:
        if not stat.S_ISREG(os.fstat(handle.fileno()).st_mode):
            raise ValueError("invalid_tls_input_file")
        data = handle.read(limit + 1)
    if len(data) > limit:
        raise ValueError("oversized_tls_input")
    return json.loads(data)


def installation_domain(value):
    if (not isinstance(value, str) or len(value) > 175 or "." not in value
            or not any(c.isalpha() for c in value)
            or any(not re.fullmatch(r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?", p) for p in value.split("."))):
        raise ValueError("invalid_installation_domain")
    return "apps." + value


def valid_host(host, namespace, domain):
    return isinstance(host, str) and bool(re.fullmatch(
        r"[a-z0-9][a-z0-9-]{0,24}-" + re.escape(namespace) + r"[a-f0-9]{20}\." + re.escape(domain), host))


def certificate_requests(projection, domain, now=None):
    now = time.time() if now is None else now
    if (projection.get("version") != 1 or projection.get("domain") != domain
            or not now < projection.get("expires", 0) <= now + 10):
        raise ValueError("stale_tls_projection")
    requests = projection.get("tls_hosts")
    if not isinstance(requests, dict) or len(requests) > 64:
        raise ValueError("invalid_tls_projection")
    if set(requests) != set(projection.get("namespaces", [])):
        raise ValueError("unmounted_tls_namespace")
    for namespace, hosts in requests.items():
        if (not re.fullmatch(r"[a-f0-9]{12}", namespace) or not isinstance(hosts, list) or len(hosts) > 100
                or any(not valid_host(host, namespace, domain) for host in hosts)):
            raise ValueError("invalid_tls_hostname")
    return {"base": [domain], **{key: sorted(set(value)) for key, value in requests.items() if value}}


def render_hosts(certificates, proxy=PROXY):
    blocks = ["# Generated by External Apps TLS; exact names only.\n"]
    for hosts, lineage in certificates:
        blocks.append("server {\n    listen 443 ssl;\n    listen [::]:443 ssl;\n"
                      + "    server_name " + " ".join(sorted(hosts)) + ";\n"
                      + f"    ssl_certificate {lineage}/fullchain.pem;\n"
                      + f"    ssl_certificate_key {lineage}/privkey.pem;\n"
                      + f"    include {proxy};\n}}\n")
    return "\n".join(blocks)


def render_ingress(hostname):
    domain = installation_domain(hostname)
    return (Path(__file__).with_name("nginx.example.conf").read_text()
            .replace("{{PUBLIC_DOMAIN}}", domain).replace("{{PUBLIC_DOMAIN_REGEX}}", re.escape(domain)))
