"""Source templates for SDK-generated Maverick apps."""

from __future__ import annotations

import json
from typing import Any

from core.app_sdk.errors import AppSdkTemplateError
from core.app_sdk.models import AppSdkCreateRequest
from core.app_sdk.template_common import normalize_entities, title_from_slug
from core.app_sdk.template_entity import entity_sqlite_files
from core.app_sdk.template_react import react_vite_files


SUPPORTED_TEMPLATES = {
    "minimal",
    "frontend-backend",
    "agent-tool",
    "data-app",
    "widget",
    "react-vite",
    "entity-sqlite",
}


def render_template_files(request: AppSdkCreateRequest) -> dict[str, str]:
    """Render all files for one SDK app template."""
    if request.template_id not in SUPPORTED_TEMPLATES:
        raise AppSdkTemplateError(f"Unknown app SDK template `{request.template_id}`.")
    contract = _contract_payload(request)
    files = {
        "app_contract.json": json.dumps(contract, indent=2, ensure_ascii=True) + "\n",
        "README.md": _readme(request),
        "tests/test_contract.py": _contract_test(request),
    }
    if request.template_id in {"frontend-backend", "data-app", "widget"}:
        files.update(_backend_files(request))
        files.update(_frontend_files(request))
    if request.template_id in {"agent-tool", "data-app"}:
        files.update(_agent_surface_files(request))
    if request.template_id == "data-app":
        files.update(_data_app_files(request))
    if request.template_id == "react-vite":
        files.update(_backend_files(request))
        files.update(react_vite_files(request))
    if request.template_id == "entity-sqlite":
        files.update(entity_sqlite_files(request))
    return files


def _contract_payload(request: AppSdkCreateRequest) -> dict[str, Any]:
    app_id = request.app_id
    has_backend = request.template_id in {"frontend-backend", "data-app", "widget"}
    if request.template_id in {"react-vite", "entity-sqlite"}:
        has_backend = True
    has_widget = request.template_id == "widget"
    has_frontend = request.template_id in {"frontend-backend", "data-app", "widget"}
    if request.template_id in {"react-vite", "entity-sqlite"}:
        has_frontend = True
    has_agent = request.template_id in {"agent-tool", "data-app", "entity-sqlite"}
    has_data_hooks = request.template_id in {"data-app", "entity-sqlite"}
    is_entity = request.template_id == "entity-sqlite"
    entities = normalize_entities(request.entities) if is_entity else []
    distribution = (
        {"mode": "workspace_local", "source_access": "editable"}
        if request.target_kind == "workspace_local"
        else {"mode": "source_available", "source_access": "forkable"}
    )
    entrypoints: dict[str, Any] = {"hooks": {}}
    if has_backend:
        entrypoints["backend"] = "backend/app_backend.py"
    if has_frontend:
        entrypoints["frontend"] = "frontend/dist"
    if has_agent:
        entrypoints["mcp"] = "mcp/server.py"
        entrypoints["cli"] = "cli/app_cli.py"
        entrypoints["skills_root"] = "skills"
    if has_data_hooks:
        entrypoints["hooks"] = {
            "install": "hooks/install.py",
            "migrate": "hooks/migrate.py",
            "health_check": "hooks/health_check.py",
        }
    return {
        "app_id": app_id,
        "contract_version": "1.0",
        "name": request.name or _title(app_id),
        "version": request.version,
        "description": request.description or f"Workspace app generated by the Maverick App SDK for `{app_id}`.",
        "publisher": request.publisher,
        "minimum_core_version": "0.1.0",
        "distribution": distribution,
        "visibility": {"platform_roles": None},
        "capabilities": {
            "mcp_tools": (
                [
                    f"{app_id}_reference_manifest",
                    f"{app_id}_list",
                    f"{app_id}_create",
                    f"{app_id}_get",
                    f"{app_id}_search",
                ]
                if is_entity
                else [f"{app_id}_reference_manifest"] if has_agent else []
            ),
            "cli_commands": [app_id] if has_agent else [],
            "skills": [f"{app_id}-ops"] if has_agent else [],
            "views": ["main"] if has_frontend else [],
            "data_events": [
                {
                    "resource": "records" if is_entity else "state",
                    "description": "Primary app records changed." if is_entity else "Primary app state changed.",
                }
            ] if has_data_hooks else [],
            "view_surfaces": [
                {
                    "view_id": "main",
                    "display_name": request.name or _title(app_id),
                    "entity_types": entities,
                    "state_actions": [],
                    "supports_custom_view": False,
                    "supports_filter_refinement": True,
                }
            ] if is_entity else [],
            "reference_entities": [
                {
                    "entity_type": entity,
                    "display_name": entity.replace("_", " ").title(),
                    "searchable": True,
                    "resolvable": True,
                    "summarizable": True,
                    "deep_link_supported": True,
                }
                for entity in entities
            ],
        },
        "entrypoints": entrypoints,
        "storage": {
            "storage_kind": "sqlite" if is_entity else "json",
            "data_schema_version": "1",
            "primary_paths": [f"data/{app_id}/app.sqlite" if is_entity else f"data/{app_id}/state.json"],
            "indices": {"kind": "embedded"} if is_entity else None,
            "supports_export": has_data_hooks,
            "supports_import": has_data_hooks,
            "supports_migrations": has_data_hooks,
        },
        "compatibility": {"workspace_modes": ["sandbox", "full-access"]},
        "hook_timeouts": {
            "install_seconds": 60,
            "upgrade_seconds": 120,
            "migrate_seconds": 300,
            "export_seconds": 120,
            "import_seconds": 120,
            "validate_after_import_seconds": 60,
            "repair_after_import_seconds": 180,
            "health_check_seconds": 30,
        },
        "lifecycle": {
            "install": has_data_hooks,
            "upgrade": True,
            "uninstall": True,
            "migrate": has_data_hooks,
            "export": False,
            "import": False,
            "validate_after_import": False,
            "repair_after_import": False,
            "rebuild": False,
            "health_check": has_data_hooks,
        },
        "health_contract": {"mode": "hook" if has_data_hooks else "none", "degraded_on_failure": True},
        "failure_semantics": {
            "install_failure": "block_activation",
            "migrate_failure": "preserve_data_mark_unhealthy",
            "import_failure": "preserve_payload_mark_failed",
        },
        "rollback_support": {"bundle": False, "data": False, "repair_only": False},
        "widgets": [
            {
                "widget_id": f"{app_id}-widget",
                "host": "base-shell",
                "content_kinds": ["shell.sidebar.primary"],
                "frontend": {
                    "kind": "iframe",
                    "mount": "frontend/dist/widgets/main",
                    "spa_fallback": True,
                },
                "actions": {"backend": has_backend, "mcp": False, "cli": False},
            }
        ] if has_widget else [],
    }


def _backend_files(request: AppSdkCreateRequest) -> dict[str, str]:
    return {
        "backend/__init__.py": "",
        "backend/app_backend.py": _backend_entrypoint(request),
        "backend/service.py": _service_module(request),
    }


def _frontend_files(request: AppSdkCreateRequest) -> dict[str, str]:
    return {
        "frontend/dist/index.html": (
            "<!doctype html>\n"
            "<html><head><meta charset=\"utf-8\"><title>{title}</title></head>\n"
            "<body><main id=\"app\"><h1>{title}</h1><button id=\"ping\">Ping backend</button>"
            "<pre id=\"result\"></pre></main>\n"
            "<script>document.getElementById('ping').onclick=async()=>{{const r=await fetch('/api/apps/{app_id}/backend',"
            "{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{action:'status'}})}});"
            "document.getElementById('result').textContent=JSON.stringify(await r.json(),null,2);}};</script>\n"
            "</body></html>\n"
        ).format(title=request.name or title_from_slug(request.app_id), app_id=request.app_id),
        **(
            {
                "frontend/dist/widgets/main/index.html": (
                    "<!doctype html>\n"
                    "<html><head><meta charset=\"utf-8\"><title>{title} Widget</title></head>\n"
                    "<body><main><strong>{title}</strong><p>Widget ready.</p></main></body></html>\n"
                ).format(title=request.name or title_from_slug(request.app_id))
            }
            if request.template_id == "widget"
            else {}
        ),
    }


def _agent_surface_files(request: AppSdkCreateRequest) -> dict[str, str]:
    skill_id = f"{request.app_id}-ops"
    return {
        "cli/app_cli.py": _cli_entrypoint(request),
        "mcp/server.py": _mcp_entrypoint(request),
        f"skills/{skill_id}/SKILL.md": _skill(request, skill_id),
    }


def _data_app_files(request: AppSdkCreateRequest) -> dict[str, str]:
    return {
        "hooks/install.py": _install_hook(),
        "hooks/migrate.py": _migrate_hook(),
        "hooks/health_check.py": _health_hook(),
    }


def _backend_entrypoint(request: AppSdkCreateRequest) -> str:
    return f'''"""Mounted backend entrypoint for `{request.app_id}`."""

from __future__ import annotations

from pathlib import Path
import sys

from core.app_sdk.runtime import backend_response, emit_json, read_entrypoint_payload

sys.path.insert(0, str(Path(__file__).resolve().parent))
from service import status_payload


payload = read_entrypoint_payload()
action = str(payload.body.get("action") or "status")
if action == "status":
    emit_json(backend_response(200, status_payload(payload)))
else:
    emit_json(backend_response(400, {{"error": f"Unsupported action `{{action}}`."}}))
'''


def _service_module(request: AppSdkCreateRequest) -> str:
    return f'''"""Service logic for `{request.app_id}`."""

from __future__ import annotations

from core.app_sdk.runtime import AppEntrypointPayload


def status_payload(payload: AppEntrypointPayload) -> dict[str, object]:
    """Return a small health/status payload for this app."""
    return {{
        "app_id": "{request.app_id}",
        "workspace_id": payload.workspace_id,
        "status": "ready",
    }}
'''


def _cli_entrypoint(request: AppSdkCreateRequest) -> str:
    return f'''"""CLI entrypoint for `{request.app_id}`."""

from __future__ import annotations

from core.app_sdk.runtime import emit_json, read_entrypoint_payload


payload = read_entrypoint_payload()
emit_json({{
    "app_id": "{request.app_id}",
    "workspace_id": payload.workspace_id,
    "command_id": payload.raw.get("command_id"),
    "reference_manifest": {{"entity_types": []}},
}})
'''


def _mcp_entrypoint(request: AppSdkCreateRequest) -> str:
    return f'''"""MCP entrypoint for `{request.app_id}`."""

from __future__ import annotations

from core.app_sdk.runtime import emit_json, read_entrypoint_payload


payload = read_entrypoint_payload()
emit_json({{
    "app_id": "{request.app_id}",
    "workspace_id": payload.workspace_id,
    "tool_name": payload.raw.get("tool_name"),
    "reference_manifest": {{"entity_types": []}},
}})
'''


def _install_hook() -> str:
    return '''"""Idempotent install hook for SDK-generated data apps."""

from __future__ import annotations

from core.app_sdk.runtime import emit_json, read_entrypoint_payload
from core.app_sdk.storage import ensure_json_state


payload = read_entrypoint_payload()
ensure_json_state(payload.data_root, "state.json", {"schema_version": "1", "items": []})
emit_json({"ok": True})
'''


def _migrate_hook() -> str:
    return '''"""Idempotent migrate hook for SDK-generated data apps."""

from __future__ import annotations

from core.app_sdk.runtime import emit_json


emit_json({"ok": True})
'''


def _health_hook() -> str:
    return '''"""Health hook for SDK-generated data apps."""

from __future__ import annotations

from pathlib import Path

from core.app_sdk.runtime import emit_json, read_entrypoint_payload


payload = read_entrypoint_payload()
if not Path(payload.data_root).exists():
    raise SystemExit("data root does not exist")
emit_json({"ok": True})
'''


def _readme(request: AppSdkCreateRequest) -> str:
    return f"""# {request.name or _title(request.app_id)}

Generated by the official Maverick App SDK.

## Validate

```bash
maverick app validate {request.app_id}
```

## Workspace-Local Install

```bash
maverick app register-local {request.app_id} --workspace {request.workspace_id or "default"}
maverick app install-local {request.app_id} --workspace {request.workspace_id or "default"}
```
"""


def _contract_test(request: AppSdkCreateRequest) -> str:
    return '''"""Generated contract smoke test."""

from __future__ import annotations

from pathlib import Path
import unittest

from core.apps.contracts import parse_app_contract_file


class GeneratedAppContractTest(unittest.TestCase):
    def test_contract_parses(self) -> None:
        app_root = Path(__file__).resolve().parents[1]
        parsed = parse_app_contract_file(app_root)
        self.assertEqual(parsed.app_id, "''' + request.app_id + '''")


if __name__ == "__main__":
    unittest.main()
'''


def _skill(request: AppSdkCreateRequest, skill_id: str) -> str:
    return f"""---
name: {skill_id}
description: Use the `{request.app_id}` Maverick app through its declared CLI and MCP surfaces.
---

# {request.name or _title(request.app_id)} Operations

Use the app's official CLI or MCP surfaces. Do not read or write another app's private data.
"""


def _title(app_id: str) -> str:
    return title_from_slug(app_id)
