export interface CalendarPreferences {
  locale: "it-IT" | "en-US";
  weekStartsOn: 0 | 1;
  hour12: boolean;
  workStart: string;
  workEnd: string;
  bufferMinutes: number;
  workDays: number[];
}
const KEY = "maverick.calendar.preferences";
export function readPreferences(): CalendarPreferences {
  const defaults: CalendarPreferences = {
    locale: (navigator.language || "en-US").startsWith("it") ? "it-IT" : "en-US",
    weekStartsOn: 1,
    hour12: false,
    workStart: "09:00",
    workEnd: "18:00",
    bufferMinutes: 0,
    workDays: [1, 2, 3, 4, 5],
  };
  try {
    return { ...defaults, ...JSON.parse(localStorage.getItem(KEY) || "{}") };
  } catch {
    return defaults;
  }
}
export function savePreferences(patch: Partial<CalendarPreferences>) {
  const value = { ...readPreferences(), ...patch };
  localStorage.setItem(KEY, JSON.stringify(value));
  window.dispatchEvent(new Event("calendar-preferences-changed"));
  return value;
}
const it: Record<string, string> = {
  "Loading calendar…": "Caricamento calendario…",
  Syncing: "Sincronizzazione",
  "Clear filters": "Cancella filtri",
  Accounts: "Account",
  Colors: "Colori",
  Categories: "Categorie",
  Filters: "Filtri",
  "Clear all": "Cancella tutti",
  Clear: "Cancella",
  Confirmed: "Confermato",
  Tentative: "Provvisorio",
  Cancelled: "Annullato",
  "Read only": "Sola lettura",
  "Local calendar": "Calendario locale",
  Local: "Locale",
  "Primary calendar": "Calendario principale",
  Meeting: "Riunione",
  Task: "Attività",
  Personal: "Personale",
  Blue: "Blu",
  Green: "Verde",
  Red: "Rosso",
  Purple: "Viola",
  Yellow: "Giallo",
  Orange: "Arancione",
  Pink: "Rosa",
  Gray: "Grigio",
  "Never synced": "Mai sincronizzato",
  "Data needs updating": "Dati da aggiornare",
  "No times proposed yet": "Nessun orario proposto",
  "Sync is partial; continue syncing to fetch remaining pages.":
    "Sincronizzazione parziale; prosegui per caricare le pagine rimanenti.",
  "Unable to load event": "Impossibile caricare l’evento",
  "Event could not be saved.": "Impossibile salvare l’evento.",
  "Title is required.": "Il titolo è obbligatorio.",
  "Start time is required.": "L’inizio è obbligatorio.",
  "End time is required.": "La fine è obbligatoria.",
  "End time must be after start time.":
    "La fine deve essere successiva all’inizio.",
  "Use Google default reminders": "Usa i promemoria predefiniti Google",
  "Select entire series to transfer this recurring event.":
    "Seleziona intera serie per trasferire questo evento ricorrente.",
  Today: "Oggi",
  Month: "Mese",
  Week: "Settimana",
  Day: "Giorno",
  List: "Agenda",
  Time: "Ora",
  "New event": "Nuovo evento",
  "Search events...": "Cerca eventi...",
  "No events found": "Nessun evento",
  "Create Event": "Crea evento",
  "Event Details": "Dettagli evento",
  Title: "Titolo",
  Description: "Descrizione",
  "Start Time": "Inizio",
  "End Time": "Fine",
  Calendar: "Calendario",
  "Account / Calendar": "Account / Calendario",
  Category: "Categoria",
  Color: "Colore",
  Tags: "Etichette",
  Save: "Salva",
  "Saving...": "Salvataggio...",
  Delete: "Elimina",
  Close: "Chiudi",
  Location: "Luogo",
  Attendees: "Partecipanti",
  Timezone: "Fuso orario",
  Status: "Stato",
  "All day": "Tutto il giorno",
  Busy: "Occupa tempo",
  Free: "Disponibile",
  "Advanced options": "Opzioni avanzate",
  Recurrence: "Ricorrenza",
  Reminder: "Promemoria",
  None: "Nessuna",
  Daily: "Giornaliera",
  Weekly: "Settimanale",
  Monthly: "Mensile",
  Yearly: "Annuale",
  "Repeat count": "Numero ripetizioni",
  "This occurrence": "Questa occorrenza",
  "This and following": "Questa e le successive",
  "Entire series": "Intera serie",
  "Find a time": "Trova un orario",
  "Working hours": "Orario lavorativo",
  "Buffer minutes": "Pausa tra eventi (minuti)",
  "Use this time": "Usa questo orario",
  Settings: "Preferenze",
  Language: "Lingua",
  "First weekday": "Primo giorno",
  "Time format": "Formato orario",
  Monday: "Lunedì",
  Sunday: "Domenica",
  Previous: "Precedente",
  Next: "Successivo",
  "Clear search": "Cancella ricerca",
  "Search all calendars": "Cerca in tutti i calendari",
  From: "Dal",
  To: "Al",
  "Load more": "Carica altri",
  "Known local events only; invitee calendars may be incomplete.":
    "Solo eventi locali conosciuti; i calendari degli invitati possono essere incompleti.",
  Show: "Mostra",
  Sync: "Sincronizza",
  Availability: "Disponibilità",
  "Sync now": "Sincronizza ora",
  Undo: "Annulla",
  "Discard unsaved changes?": "Scartare le modifiche non salvate?",
  "Event deleted": "Evento eliminato",
  "Keep draft and retry with latest revision":
    "Mantieni la bozza e riprova sulla versione aggiornata",
  "Reload latest event": "Carica la versione aggiornata",
  "Another version is available. Your draft has been kept.":
    "È disponibile una nuova versione. La bozza è stata conservata.",
  "End date is exclusive": "La data finale è esclusiva",
  Connect: "Connetti",
  Connecting: "Connessione...",
  "Local reminders are saved in Maverick notifications, even when Calendar is closed.":
    "I promemoria locali vengono conservati nelle notifiche Maverick, anche con Calendar chiuso.",
  "Overlapping events": "Eventi sovrapposti",
  "Event title": "Titolo evento",
  "Event description": "Descrizione evento",
  "Changing timezone keeps the same civil dates.": "Cambiare fuso mantiene le stesse date civili.",
  "Reminder minutes must be a whole number from 0 to 40320.": "I minuti del promemoria devono essere un numero intero fra 0 e 40320.",
  "Yes": "Sì",
  "No": "No",
  "Edit event": "Modifica evento",
  "Cancel edit": "Annulla modifiche",
  "When": "Quando",
  "First day": "Primo giorno",
  "Last day included": "Ultimo giorno incluso",
  "days": "giorni",
  "minutes": "minuti",
  "Changing timezone keeps the same instant; the displayed clock time changes.": "Cambiare fuso mantiene lo stesso istante; cambia l’orario visualizzato.",
  "Reminders": "Promemoria",
  "Minutes before": "Minuti prima",
  "Delivery": "Invio",
  "Notification": "Notifica",
  "Remove reminder": "Rimuovi promemoria",
  "Remove": "Rimuovi",
  "No reminders": "Nessun promemoria",
  "Add reminder": "Aggiungi promemoria",
  "Accepted": "Accettato",
  "Declined": "Rifiutato",
  "Awaiting response": "In attesa di risposta",
  "Response unknown": "Risposta non disponibile",
  "Organizer": "Organizzatore",
  "Optional": "Facoltativo",
  "Remove participant": "Rimuovi partecipante",
  "Name or email": "Nome o email",
  "Display name": "Nome visualizzato",
  "Add participant": "Aggiungi partecipante",
  "Enter a valid email address": "Inserisci un indirizzo email valido",
  "Participant already added": "Partecipante già aggiunto",
  "Google invitees require email addresses. Responses are shown as received from Google.": "Gli invitati Google richiedono un indirizzo email. Le risposte sono quelle ricevute da Google.",
  "Local participants are notes; Maverick does not send invitations.": "I partecipanti locali sono annotazioni; Maverick non invia inviti.",
  "Custom recurrence": "Ricorrenza personalizzata",
  "Repeating event": "Evento ricorrente",
  "occurrences": "occorrenze",
  "Until": "Fino al",
  "No end date": "Senza data finale",
  "Every": "Ogni",
  "Apply changes to": "Applica le modifiche a",
  "Edit this and following or the entire series to change repetition.": "Per cambiare la ripetizione seleziona questa e le successive o l’intera serie.",
  "Frequency": "Frequenza",
  "Repeat every": "Ripeti ogni",
  "Days": "Giorni",
  "Ends": "Termina",
  "After occurrences": "Dopo un numero di occorrenze",
  "On date": "In data",
  "Advanced recurrence rules": "Regole avanzate di ricorrenza",
  "Editable": "Modificabile",
  "Last sync": "Ultima sincronizzazione",
  "Partial sync": "Sincronizzazione parziale",
  "This connected account has read-only access to the calendar.": "Questo account connesso può soltanto leggere il calendario.",
  "Open in Google Calendar": "Apri in Google Calendar",
  "Join call": "Partecipa alla chiamata",
  "Conference": "Conferenza",
  "Open map": "Apri mappa",
  "minutes before": "minuti prima",
  "Classification": "Classificazione",
  "Classification and availability": "Classificazione e disponibilità",
  "New tag": "Nuova etichetta",
  "Add tag": "Aggiungi etichetta",
  "Find free days": "Trova giornate libere",
  "Choose a valid search interval": "Scegli un intervallo di ricerca valido",
  "Availability failed": "Verifica disponibilità non riuscita",
  "No free times in this interval": "Nessun orario libero in questo intervallo",
  "Your draft": "La tua bozza",
  "Current version": "Versione corrente",
  "Use my changes for conflicting fields": "Usa le mie modifiche nei campi in conflitto",
  "Merge my changes with latest version": "Unisci le mie modifiche alla versione corrente",
  "Review overlapping events before saving.": "Controlla gli eventi sovrapposti prima di salvare.",
  "Save with overlaps": "Salva con le sovrapposizioni",
};
export function t(text: string): string {
  return readPreferences().locale === "it-IT" ? it[text] || text : text;
}
export function formatCalendarDate(
  date: Date,
  options: Intl.DateTimeFormatOptions,
) {
  return date.toLocaleDateString(readPreferences().locale, options);
}
export function formatCalendarTime(date: Date) {
  return date.toLocaleTimeString(readPreferences().locale, {
    hour: "2-digit",
    minute: "2-digit",
    hour12: readPreferences().hour12,
  });
}
