#!/usr/bin/env python3
"""Deterministic ACP peer used only by the rejected G3 option-A spike.

The fixture deliberately has no model or tool loop.  It proves that the pinned
OpenDesign ACP transport can stream, resume, cancel, and write a project file,
while recording which run identity (if any) OpenDesign actually supplies.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import sys
import threading
import time
from typing import Any


_OUTPUT_LOCK = threading.Lock()
_CANCELLED = threading.Event()
_TRACE_PATH = os.environ.get("MAVERICK_ACP_SPIKE_TRACE", "").strip()
_CWD: Path | None = None
_SESSION_ID = "maverick-acp-spike-session"


def _send(payload: dict[str, Any]) -> None:
    with _OUTPUT_LOCK:
        sys.stdout.write(json.dumps(payload, separators=(",", ":")) + "\n")
        sys.stdout.flush()


def _trace(event: str, **details: Any) -> None:
    if not _TRACE_PATH:
        return
    record = {"event": event, **details}
    path = Path(_TRACE_PATH)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(record, sort_keys=True) + "\n")


def _provider_secret_names() -> list[str]:
    markers = ("API_KEY", "ACCESS_TOKEN", "SECRET_KEY", "AUTH_TOKEN")
    return sorted(key for key in os.environ if any(marker in key for marker in markers))


def _prompt_text(params: object) -> str:
    if not isinstance(params, dict):
        return ""
    blocks = params.get("prompt")
    if not isinstance(blocks, list):
        return ""
    return " ".join(
        str(block.get("text", ""))
        for block in blocks
        if isinstance(block, dict) and block.get("type") == "text"
    )


def _run_prompt(request_id: object, prompt: str) -> None:
    if "MAVERICK_SPIKE_TIMEOUT" in prompt:
        _trace("prompt_timeout_started")
        _CANCELLED.wait(5)
        return
    _send(
        {
            "method": "session/update",
            "params": {
                "update": {
                    "sessionUpdate": "agent_message_chunk",
                    "content": {"type": "text", "text": "first-sse-before-terminal"},
                }
            },
        }
    )
    _trace(
        "first_update",
        prompt_kind="long" if "MAVERICK_SPIKE_LONG" in prompt else "short",
    )

    if "MAVERICK_SPIKE_LONG" in prompt:
        for _ in range(300):
            if _CANCELLED.wait(0.05):
                _trace("prompt_cancelled")
                return
        _send({"id": request_id, "result": {"stopReason": "end_turn"}})
        return

    time.sleep(0.15)
    if "MAVERICK_SPIKE_FAIL" in prompt:
        _send(
            {
                "id": request_id,
                "error": {"code": -32001, "message": "intentional spike failure"},
            }
        )
        _trace("prompt_failed")
        return

    if _CWD is None:
        _send({"id": request_id, "error": {"code": -32002, "message": "missing cwd"}})
        return
    output = _CWD / (
        "maverick-resume.html"
        if "MAVERICK_SPIKE_RESUME" in prompt
        else "maverick-spike.html"
    )
    output.write_text("<main>generated by Maverick ACP transport spike</main>\n", encoding="utf-8")
    _send(
        {
            "method": "session/update",
            "params": {
                "update": {
                    "sessionUpdate": "agent_message_chunk",
                    "content": {"type": "text", "text": " terminal-success"},
                }
            },
        }
    )
    _send(
        {
            "id": request_id,
            "result": {
                "stopReason": "end_turn",
                "usage": {"inputTokens": 1, "outputTokens": 2},
            },
        }
    )
    _trace("prompt_succeeded", file_name=output.name)


def _handle(message: dict[str, Any]) -> None:
    global _CWD
    request_id = message.get("id")
    method = message.get("method")
    params = message.get("params")
    _trace("rpc", method=method)
    if method == "initialize":
        _send({"id": request_id, "result": {"protocolVersion": 1}})
        return
    if method == "session/new":
        if isinstance(params, dict) and isinstance(params.get("cwd"), str):
            _CWD = Path(params["cwd"])
        _trace(
            "session_new",
            param_keys=sorted(params) if isinstance(params, dict) else [],
            open_design_run_id=os.environ.get("OPEN_DESIGN_RUN_ID"),
            provider_secret_names=_provider_secret_names(),
        )
        _send(
            {
                "id": request_id,
                "result": {
                    "sessionId": _SESSION_ID,
                    "openCodeSessionId": "maverick-durable-spike-session",
                },
            }
        )
        return
    if method == "session/load":
        _trace("session_load", param_keys=sorted(params) if isinstance(params, dict) else [])
        _send({"id": request_id, "result": {"sessionId": _SESSION_ID}})
        return
    if method == "session/prompt":
        threading.Thread(
            target=_run_prompt,
            args=(request_id, _prompt_text(params)),
            daemon=True,
        ).start()
        return
    if method == "session/cancel":
        _CANCELLED.set()
        _trace("session_cancel", param_keys=sorted(params) if isinstance(params, dict) else [])
        _send({"id": request_id, "result": {}})
        return
    _send({"id": request_id, "error": {"code": -32601, "message": "method not found"}})


def main() -> int:
    if "--version" in sys.argv:
        print("maverick-acp-spike 1.0")
        return 0
    if len(sys.argv) < 2 or sys.argv[1] != "acp":
        print("expected acp", file=sys.stderr)
        return 2
    _trace("started", argv=sys.argv[1:], provider_secret_names=_provider_secret_names())
    for raw_line in sys.stdin:
        try:
            message = json.loads(raw_line)
        except json.JSONDecodeError:
            continue
        if isinstance(message, dict):
            _handle(message)
    _CANCELLED.set()
    _trace("stdin_closed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
