"""CRM backend action catalog and write-event mapping."""

from __future__ import annotations

from typing import Any
from entity_catalog import ENTITY_TABLES


MCP_TOOL_ACTIONS = {
    "crm_integration_prepare": "crm.integration_prepare",
    "crm_integration_run": "crm.integration_run",
    "crm_integration_retry": "crm.integration_retry",
    "crm_integration_search": "crm.integration_search",
    "crm_integration_link": "crm.integration_link",
    "crm_integration_reconcile": "crm.integration_reconcile",
    "crm_integration_get": "crm.integration_get",
    "crm_integration_list": "crm.integration_list",
    "crm_integration_refresh": "crm.integration_refresh",
    "crm_meeting_brief": "crm.meeting_brief",
    "crm_meeting_outcome": "crm.meeting_outcome",
    "crm_extension_schema": "crm.extension_schema",
    "crm_list_extension_records": "crm.list_extension_records",
    "crm_create_extension_record": "crm.create_extension_record",
    "crm_update_extension_record": "crm.update_extension_record",
    "crm_link_records": "crm.link_records",
    "crm_unlink_records": "crm.unlink_records",
    "crm_record_context": "crm.record_context",
    "crm_overview": "crm.overview",
    "crm_integration_context": "crm.integration_context",
    "crm_link_provider_record": "crm.link_provider_record",
    "crm_import_plan": "crm.import_plan",
    "crm_import_apply": "crm.import_apply",
    "crm_import_jobs": "crm.import_jobs",
    "crm_search": "crm.search",
    "crm_get_record": "crm.get_record",
    "crm_create_lead": "crm.create_lead",
    "crm_website_intake": "crm.website_intake",
    "crm_update_lead": "crm.update_lead",
    "crm_convert_lead": "crm.convert_lead",
    "crm_create_contact": "crm.create_contact",
    "crm_update_contact": "crm.update_contact",
    "crm_create_account": "crm.create_account",
    "crm_update_account": "crm.update_account",
    "crm_create_deal": "crm.create_deal",
    "crm_update_deal": "crm.update_deal",
    "crm_move_deal": "crm.move_deal",
    "crm_create_pipeline": "crm.create_pipeline",
    "crm_update_pipeline": "crm.update_pipeline",
    "crm_create_pipeline_stage": "crm.create_pipeline_stage",
    "crm_update_pipeline_stage": "crm.update_pipeline_stage",
    "crm_log_activity": "crm.log_activity",
    "crm_create_task": "crm.create_task",
    "crm_update_task": "crm.update_task",
    "crm_create_note": "crm.create_note",
    "crm_update_note": "crm.update_note",
    "crm_archive_record": "crm.archive_record",
    "crm_unarchive_record": "crm.unarchive_record",
    "crm_delete_record": "crm.delete_record",
    "crm_tag_record": "crm.tag_record",
    "crm_untag_record": "crm.untag_record",
    "crm_bulk_update": "crm.bulk_update",
    "crm_merge_records": "crm.merge_records",
    "crm_timeline": "crm.timeline",
    "crm_audit_log": "crm.audit_log",
    "crm_sales_reports": "crm.sales_reports",
    "crm_filter_records": "crm.filter_records",
    "crm_find_duplicates": "crm.find_duplicates",
    "crm_schema": "crm.schema",
    "crm_list_custom_fields": "crm.list_custom_fields",
    "crm_set_custom_fields": "crm.set_custom_fields",
    "crm_record_enrichment": "crm.record_enrichment",
    "crm_intelligent_next_actions": "crm.intelligent_next_actions",
    "crm_propose_workflows": "crm.propose_workflows",
    "crm_list_workflow_proposals": "crm.list_workflow_proposals",
    "crm_approve_workflow_proposal": "crm.approve_workflow_proposal",
    "crm_dismiss_workflow_proposal": "crm.dismiss_workflow_proposal",
    "crm_reject_workflow_proposal": "crm.reject_workflow_proposal",
    "crm_apply_workflow_proposal": "crm.apply_workflow_proposal",
    "crm_link_external_ref": "crm.link_external_ref",
    "crm_unlink_external_ref": "crm.unlink_external_ref",
    "crm_list_external_refs": "crm.list_external_refs",
    "crm_external_timeline": "crm.external_timeline",
    "crm_list_next_actions": "crm.list_next_actions",
    "crm_summarize_account": "crm.summarize_account",
    "crm_account_brief": "crm.account_brief",
    "crm_export": "crm.export",
    "crm_import_preview": "crm.import_preview",
    "crm_import_commit": "crm.import_commit",
    "crm_health": "crm.health",
    "crm_view_filter": "crm.view_filter",
    "crm_set_view_filter": "crm.set_view_filter",
    "crm_set_custom_view": "crm.set_custom_view",
    "crm_clear_custom_view": "crm.clear_custom_view",
    "crm_reference_manifest": "crm_reference_manifest",
    "crm_reference_search": "crm_reference_search",
    "crm_reference_resolve": "crm_reference_resolve",
    "crm_reference_summarize": "crm_reference_summarize",
}


UI_HELPER_ACTIONS = [
    "crm.workspace_view",
    "crm.pipeline_board",
    "crm.operations_feed",
    "crm.workflow_proposal_preview",
    "crm.list_saved_views",
    "crm.save_view",
    "crm.delete_saved_view",
    "crm.apply_saved_view",
    "crm.delete_pipeline_stage",
    "crm.view_filter",
    "crm.set_view_filter",
    "crm.set_custom_view",
    "crm.clear_custom_view",
]


CONFIG_HELPER_ACTIONS = [
    "crm.define_custom_field",
    "crm.archive_custom_field",
    "crm.list_automation_rules",
    "crm.create_automation_rule",
    "crm.update_automation_rule",
    "crm.run_automation_rules",
]


WRITE_ACTIONS = {
    "crm.integration_prepare",
    "crm.integration_run",
    "crm.integration_retry",
    "crm.integration_search",
    "crm.integration_link",
    "crm.integration_reconcile",
    "crm.integration_refresh",
    "crm.meeting_outcome",
    "crm.integration_callback",
    "crm.integration_tick",
    "crm.create_extension_record",
    "crm.update_extension_record",
    "crm.link_records",
    "crm.unlink_records",
    "crm.link_provider_record",
    "crm.import_apply",
    "crm.create_account",
    "create_account",
    "crm.update_account",
    "update_account",
    "crm.create_lead",
    "create_lead",
    "crm.website_intake",
    "crm.ingest_website_intake",
    "website_intake",
    "crm.update_lead",
    "update_lead",
    "crm.convert_lead",
    "convert_lead",
    "crm.create_contact",
    "create_contact",
    "crm.update_contact",
    "update_contact",
    "crm.create_deal",
    "create_deal",
    "crm.update_deal",
    "update_deal",
    "crm.move_deal",
    "move_deal",
    "crm.create_pipeline",
    "create_pipeline",
    "crm.update_pipeline",
    "update_pipeline",
    "crm.create_pipeline_stage",
    "create_pipeline_stage",
    "crm.update_pipeline_stage",
    "update_pipeline_stage",
    "crm.delete_pipeline_stage",
    "delete_pipeline_stage",
    "crm.log_activity",
    "log_activity",
    "crm.create_task",
    "create_task",
    "crm.update_task",
    "update_task",
    "crm.create_note",
    "create_note",
    "crm.update_note",
    "update_note",
    "crm.archive_record",
    "archive_record",
    "crm.unarchive_record",
    "unarchive_record",
    "crm.delete_record",
    "delete_record",
    "crm.tag_record",
    "tag_record",
    "crm.untag_record",
    "untag_record",
    "crm.bulk_update",
    "bulk_update",
    "crm.merge_records",
    "merge_records",
    "crm_merge_records",
    "crm.import_commit",
    "import_commit",
    "crm.save_view",
    "save_view",
    "crm.delete_saved_view",
    "delete_saved_view",
    "crm.apply_saved_view",
    "apply_saved_view",
    "crm.define_custom_field",
    "define_custom_field",
    "crm.archive_custom_field",
    "archive_custom_field",
    "crm.set_custom_fields",
    "set_custom_fields",
    "crm.create_automation_rule",
    "create_automation_rule",
    "crm.update_automation_rule",
    "update_automation_rule",
    "crm.record_enrichment",
    "record_enrichment",
    "crm.propose_workflows",
    "propose_workflows",
    "crm.run_automation_rules",
    "run_automation_rules",
    "crm.approve_workflow_proposal",
    "approve_workflow_proposal",
    "crm.dismiss_workflow_proposal",
    "dismiss_workflow_proposal",
    "crm.reject_workflow_proposal",
    "reject_workflow_proposal",
    "crm.apply_workflow_proposal",
    "apply_workflow_proposal",
    "crm.link_external_ref",
    "link_external_ref",
    "crm_link_external_ref",
    "crm.unlink_external_ref",
    "unlink_external_ref",
    "crm_unlink_external_ref",
    "crm.set_view_filter",
    "set_view_filter",
    "crm.set_custom_view",
    "set_custom_view",
    "crm.clear_custom_view",
    "clear_custom_view",
}


def app_events_for_action(action: str) -> list[dict[str, str]]:
    if action in WRITE_ACTIONS:
        resource = "view-state" if "view" in action or "custom_view" in action else "records"
        return [{"type": "maverick.app.data-changed", "owner_app_id": "crm", "resource": resource}]
    return []


def operations_manifest() -> dict[str, Any]:
    return {
        "ok": True,
        "app_id": "crm",
        "default_action": "operations.manifest",
        "entities": list(ENTITY_TABLES),
        "actions": [
            "crm.integration_prepare",
            "crm.integration_run",
            "crm.integration_retry",
            "crm.integration_search",
            "crm.integration_link",
            "crm.integration_reconcile",
            "crm.integration_get",
            "crm.integration_list",
            "crm.integration_refresh",
            "crm.meeting_brief",
            "crm.meeting_outcome",
            "crm.extension_schema",
            "crm.list_extension_records",
            "crm.create_extension_record",
            "crm.update_extension_record",
            "crm.link_records",
            "crm.unlink_records",
            "crm.record_context",
            "crm.overview",
            "crm.workspace_view",
            "crm.integration_context",
            "crm.link_provider_record",
            "crm.import_plan",
            "crm.import_apply",
            "crm.import_jobs",
            "crm.search",
            "crm.records_table",
            "crm.get_record",
            "crm.create_lead",
            "crm.website_intake",
            "crm.update_lead",
            "crm.convert_lead",
            "crm.create_contact",
            "crm.update_contact",
            "crm.create_account",
            "crm.update_account",
            "crm.create_deal",
            "crm.update_deal",
            "crm.move_deal",
            "crm.pipeline_board",
            "crm.create_pipeline",
            "crm.update_pipeline",
            "crm.create_pipeline_stage",
            "crm.update_pipeline_stage",
            "crm.delete_pipeline_stage",
            "crm.log_activity",
            "crm.create_task",
            "crm.update_task",
            "crm.create_note",
            "crm.update_note",
            "crm.archive_record",
            "crm.unarchive_record",
            "crm.delete_record",
            "crm.tag_record",
            "crm.untag_record",
            "crm.bulk_update",
            "crm.merge_records",
            "crm.timeline",
            "crm.audit_log",
            "crm.sales_reports",
            "crm.filter_records",
            "crm.find_duplicates",
            "crm.list_saved_views",
            "crm.save_view",
            "crm.delete_saved_view",
            "crm.apply_saved_view",
            "crm.schema",
            "crm.list_custom_fields",
            "crm.define_custom_field",
            "crm.archive_custom_field",
            "crm.set_custom_fields",
            "crm.list_automation_rules",
            "crm.create_automation_rule",
            "crm.update_automation_rule",
            "crm.record_enrichment",
            "crm.intelligent_next_actions",
            "crm.propose_workflows",
            "crm.run_automation_rules",
            "crm.list_workflow_proposals",
            "crm.workflow_proposal_preview",
            "crm.approve_workflow_proposal",
            "crm.dismiss_workflow_proposal",
            "crm.reject_workflow_proposal",
            "crm.apply_workflow_proposal",
            "crm.link_external_ref",
            "crm.unlink_external_ref",
            "crm.list_external_refs",
            "crm.external_timeline",
            "crm.list_next_actions",
            "crm.operations_feed",
            "crm.summarize_account",
            "crm.account_brief",
            "crm.import_preview",
            "crm.import_commit",
            "crm.export",
            "crm.health",
            "crm.view_filter",
            "crm.set_view_filter",
            "crm.set_custom_view",
            "crm.clear_custom_view",
            "crm_reference_manifest",
            "crm_reference_search",
            "crm_reference_resolve",
            "crm_reference_summarize",
        ],
        "mcp_actions": list(MCP_TOOL_ACTIONS.values()),
        "ui_helper_actions": UI_HELPER_ACTIONS,
        "config_helper_actions": CONFIG_HELPER_ACTIONS,
    }
